{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if ezmodule( 'ezjscore' )}
    <input type="submit" value="{'Upload a file'|i18n( 'design/admin/content/datatype' )}"
            name="RelationUploadNew{$attribute.id}-{$attribute.version}"
            class="button simple-relation-upload-new hide"
            {cond( $enabled, '', 'disabled="disabled"' )}
            title="{'Upload a file to create a new object and add it to the relation'|i18n( 'design/admin/content/datatype' )}" />

    {run-once}
    {* The upload dialog: Exponential UI (exp::io, exp::dialog, exp::upload in BackendJavaScriptList) runs the steps
       and server calls on jQuery 4 (expajaxuploader.js). *}
    {ezscript_require( 'expajaxuploader.js' )}
    <script type="text/javascript">
    {literal}
    (function () {
        if (!window.Exp || !window.Exp.ready) { return; }
        Exp.ready(function ($) {
            if (!$.fn.expAjaxUploader) { return; }
            $('.simple-relation-upload-new').expAjaxUploader({
                open: {
                    action: 'ezajaxuploader::uploadform::ezobjectrelation'
                },
                upload: {
                    action: 'ezajaxuploader::upload::ezobjectrelation?ContentType=html',
                    form: 'form.ajaxuploader-upload'
                },
                location: {
                    action: 'ezajaxuploader::preview::ezobjectrelation',
                    form: 'form.ajaxuploader-location',
                    browse: 'div.ajaxuploader-browse',
        {/literal}
                    required: "{'Please choose a location'|i18n( 'design/admin/content/datatype' )|wash( 'javascript' )}"
        {literal}
                },
                preview: {
                    form: 'form.ajaxuploader-preview',

                    // this is the uploader: the object just created goes into the relation
                    callback: function () {
                        var box = $('#ezobjectrelation_browse_' + this.conf.target.ObjectRelationsAttributeId),
                            table = box.find('table.list').first(),
                            tds = table.find('tbody').first().children().last().children(),
                            result = this.lastMetaData;

                        table.removeClass('hide');
                        tds.eq(0).text(result.object_info.name);
                        tds.eq(1).text(result.object_info.class_name);
                        tds.eq(2).text(result.object_info.section_name);
                        tds.eq(3).text(result.object_info.published);

                        box.find('input[name*=_data_object_relation_id_]').first().val(result.object_info.id);
                        box.find('.ezobject-relation-remove-button').first().removeClass('button-disabled').addClass('button').prop('disabled', false);
                        box.find('.ezobject-relation-no-relation').addClass('hide');
                        box.find('.ezobject-relation-add-button').first().addClass('button-disabled').prop('disabled', true);
                        box.find('.simple-relation-upload-new').first().addClass('button-disabled').prop('disabled', true);

                        this.close();
                    }
                },
        {/literal}
                validationErrorText: "{'Some required fields are empty.'|i18n( 'design/admin/content/datatype' )|wash( 'javascript' )}",
                parseJSONErrorText: "{'Unable to parse the JSON response.'|i18n( 'design/admin/content/datatype' )|wash( 'javascript' )}",
                title: "{'Upload a file and add the resulting object in the relation'|i18n( 'design/admin/content/datatype' )|wash( 'javascript' )}"
        {literal}
            });
        });
    })();
    {/literal}
    </script>
    {/run-once}
{/if}
