{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* The import step of package/compare (package/compare.tpl, kernel/package/compare.php,
   eZPackageComparisonImport): either the confirmation or the result.
   The confirmation lists every chosen item with a tick of its own (untick it to leave the item out),
   what the import sets and keeps, and, folded, one tick per value the import would set (untick one
   to keep the site's value; a value that can only be imported with the item is ticked and fixed),
   with All/None per item. It posts ImportInclude[] (items), ImportValueShown[] and ImportValue[]
   ("<item>|<language>/<identifier>"), and ImportRemoteID[<item>] (what each item stood for).
   The result lists each item imported, failed or not imported, with its values set and kept, and
   the next step of an "all changes of this filter" import when more are left.
   Everything from the package is escaped.
   Parameters: compare - $Compare; import - $Compare.import; glyphs - the status glyphs. *}
{def $resultLabels = hash( 'done', 'Imported'|i18n('design/admin/package'),
                           'failed', 'Failed'|i18n('design/admin/package'),
                           'skipped', 'Not imported'|i18n('design/admin/package') )
     $resultGlyphs = hash( 'done', '✓', 'failed', '!', 'skipped', '–' )
     $confirm = $import.step|eq('confirm')}
<section class="pcmp-import pcmp-import-{$import.step|wash}" aria-labelledby="pcmp-import-title">
    {if $confirm}
    <h2 id="pcmp-import-title">{'Import from the package: confirm'|i18n('design/admin/package')}</h2>
    <p class="pcmp-import-lead">
        {'%count of %total chosen item(s) can be imported. The site gets what the package brings for them; nothing is removed.'|i18n('design/admin/package',,hash('%count', $import.importable, '%total', $import.entries|count))|wash}
        {'Untick an item to leave it out, or open its values to keep single ones as the site has them.'|i18n('design/admin/package')}
        {if $import.importable|gt( $import.max )}<strong>{'At most %max are imported in this step; the rest stays for the next one.'|i18n('design/admin/package',,hash('%max', $import.max))|wash}</strong>{/if}
        {if $import.mode|eq('filter')}{'All changes of this filter: %count item(s) in all, taken %max at a time.'|i18n('design/admin/package',,hash('%count', $import.filter_total, '%max', $import.max))|wash}{/if}
    </p>
    {else}
    <h2 id="pcmp-import-title">{'Import from the package: result'|i18n('design/admin/package')}</h2>
    <p class="pcmp-import-lead">{'%done imported, %failed failed. The comparison below is up to date for them.'|i18n('design/admin/package',,hash('%done', $import.done, '%failed', $import.failed))|wash}
        {if and( is_set( $import.left_out ), $import.left_out|gt(0) )}{'%count item(s) left out by you.'|i18n('design/admin/package',,hash('%count', $import.left_out))|wash}{/if}</p>
    {/if}

    <form method="post" action={$compare.url_post|ezurl}>
    <ol class="pcmp-import-list">
    {foreach $import.entries as $entry}
        {def $setCount = 0 $keptCount = 0}
        {foreach $entry.values as $value}{if $value.ticked}{set $setCount = inc( $setCount )}{else}{set $keptCount = inc( $keptCount )}{/if}{/foreach}
        <li class="pcmp-import-entry{if is_set( $entry.result )} pcmp-result-{$entry.result|wash}{elseif $entry.importable|not} pcmp-result-skipped{/if}">
            <div class="pcmp-import-entry-head">
                {if and( $confirm, $entry.importable )}
                <label class="pcmp-import-include" title="{'Untick to leave this item out'|i18n('design/admin/package')}"><input type="checkbox" name="ImportInclude[]" value="{$entry.index|wash}" checked="checked" /><span class="pvf-hidden">{'Import %name'|i18n('design/admin/package',,hash('%name', $entry.name))|wash}</span></label>
                <input type="hidden" name="ImportRemoteID[{$entry.index|wash}]" value="{$entry.remote_id|wash}" />
                {/if}
                <span class="pcmp-status pcmp-status-{$entry.status|wash}"><span class="pcmp-glyph" aria-hidden="true">{$glyphs[$entry.status]}</span> {$compare.status_labels[$entry.status]|wash}</span>
                <span class="pvf-kind pvf-kind-{$entry.kind|wash}">{if $entry.kind|eq('class')}{'Class'|i18n('design/admin/package')}{else}{'Object'|i18n('design/admin/package')}{/if}</span>
                <strong class="pcmp-import-name">{$entry.name|wash}</strong>
                {if $entry.class_identifier}<code>{$entry.class_identifier|wash}</code>{/if}
                {if is_set( $entry.result )}
                <span class="pcmp-result pcmp-result-badge-{$entry.result|wash}"><span aria-hidden="true">{$resultGlyphs[$entry.result]}</span> {$resultLabels[$entry.result]|wash}</span>
                {elseif $entry.importable|not}
                <span class="pcmp-result pcmp-result-badge-skipped"><span aria-hidden="true">–</span> {'Cannot be imported'|i18n('design/admin/package')}</span>
                {/if}
            </div>
            {if and( is_set( $entry.result ), $entry.result|ne('done') )}<p class="pcmp-import-reason">{$entry.message|wash}</p>
            {elseif $entry.importable|not}<p class="pcmp-import-reason">{$entry.reason|wash}</p>{/if}
            {if $entry.importable}
            {if $entry.changes|count|gt(0)}
            <ul class="pcmp-import-changes">
                {foreach $entry.changes as $line}<li><span class="pcmp-glyph" aria-hidden="true">+</span> {$line|wash}</li>{/foreach}
            </ul>
            {/if}
            {if $entry.values|count|gt(0)}
            <details class="pcmp-values">
                <summary>{if $confirm}{'Values (%count): choose which to import'|i18n('design/admin/package',,hash('%count', $entry.values|count))|wash}{else}{'Values: %set from the package, %kept kept as on the site'|i18n('design/admin/package',,hash('%set', $setCount, '%kept', $keptCount))|wash}{/if}</summary>
                {if $confirm}<p class="pcmp-values-all" hidden><button type="button" class="pvf-link-button" data-pcmp-values="all">{'All'|i18n('design/admin/package')}</button> <button type="button" class="pvf-link-button" data-pcmp-values="none">{'None'|i18n('design/admin/package')}</button></p>{/if}
                <ul class="pcmp-values-list">
                {foreach $entry.values as $value}
                    <li>{if $confirm}<label{if $value.untickable|not} title="{'This value can only be imported together with the item'|i18n('design/admin/package')}"{/if}><input type="checkbox" name="ImportValue[]" value="{concat( $entry.index, '|', $value.key )|wash}"{if $value.ticked} checked="checked"{/if}{if $value.untickable|not} disabled="disabled"{/if} /> {$value.label|wash}{if $value.new_translation} <span class="pcmp-state pcmp-state-package_only">{'New translation'|i18n('design/admin/package')}</span>{/if}</label>
                        {if $value.untickable}<input type="hidden" name="ImportValueShown[]" value="{concat( $entry.index, '|', $value.key )|wash}" />{/if}
                    {else}<span class="pcmp-glyph" aria-hidden="true">{if $value.ticked}+{else}={/if}</span> {$value.label|wash}{if $value.ticked|not} <span class="pcmp-values-kept">({'kept as on the site'|i18n('design/admin/package')})</span>{/if}{/if}</li>
                {/foreach}
                </ul>
            </details>
            {/if}
            {if $entry.kept|count|gt(0)}
            <ul class="pcmp-import-kept">
                {foreach $entry.kept as $line}<li><span class="pcmp-glyph" aria-hidden="true">=</span> {$line|wash}</li>{/foreach}
            </ul>
            {/if}
            {/if}
        </li>
        {undef $setCount $keptCount}
    {/foreach}
    </ol>
    {if $confirm}
    <input type="hidden" name="ImportMode" value="{$import.mode|wash}" />
    <div class="pcmp-import-actions">
        <input class="defaultbutton{if $import.importable|eq(0)} button-disabled{/if}" type="submit" name="ConfirmImportButton" value="{'Import the ticked items'|i18n('design/admin/package')}"{if $import.importable|eq(0)} disabled="disabled"{/if} />
        <input class="button" type="submit" name="CancelImportButton" value="{'Cancel'|i18n('design/admin/package')}" />
    </div>
    {elseif and( $import.mode|eq('filter'), $import.remaining|gt(0) )}
    <div class="pcmp-import-actions">
        <input class="defaultbutton" type="submit" name="ImportFilterButton" value="{'Import the next ones (%count left in this filter)'|i18n('design/admin/package',,hash('%count', $import.remaining))|wash}" />
    </div>
    {/if}
    </form>
</section>
{if $confirm}
{* All/None per item: a convenience on top of the plain checkboxes, shown only where scripts run *}
<script>
(function () {ldelim}
    var blocks = document.querySelectorAll( '.pcmp-import details.pcmp-values' );
    for ( var i = 0; i < blocks.length; i++ )
    {ldelim}
        var bar = blocks[i].querySelector( '.pcmp-values-all' );
        if ( !bar ) continue;
        bar.hidden = false;
        bar.addEventListener( 'click', function ( event )
        {ldelim}
            var mode = event.target.getAttribute( 'data-pcmp-values' );
            if ( !mode ) return;
            var boxes = this.parentNode.querySelectorAll( 'input[name="ImportValue[]"]:not([disabled])' );
            for ( var j = 0; j < boxes.length; j++ ) boxes[j].checked = mode === 'all';
        {rdelim} );
    {rdelim}
{rdelim})();
</script>
{/if}
{undef $resultLabels $resultGlyphs $confirm}
