{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* The import step of package/compare (package/compare.tpl, kernel/package/compare.php,
   eZPackageComparisonImport): either the confirmation, which lists exactly what an import of the
   chosen items would set and keep and why an item cannot be imported, with Confirm and Cancel; or
   the result of an import, item by item, with the next step of an "all changes of this filter"
   import when more are left. Everything from the package is escaped.
   Parameters: compare - $Compare; import - $Compare.import; glyphs - the status glyphs. *}
{def $resultLabels = hash( 'done', 'Imported'|i18n('design/admin/package'),
                           'failed', 'Failed'|i18n('design/admin/package'),
                           'skipped', 'Not imported'|i18n('design/admin/package') )
     $resultGlyphs = hash( 'done', '✓', 'failed', '!', 'skipped', '–' )}
<section class="pcmp-import pcmp-import-{$import.step|wash}" aria-labelledby="pcmp-import-title">
    {if $import.step|eq('confirm')}
    <h2 id="pcmp-import-title">{'Import from the package: confirm'|i18n('design/admin/package')}</h2>
    <p class="pcmp-import-lead">
        {'%count of %total chosen item(s) can be imported. The site gets what the package brings for them; nothing is removed.'|i18n('design/admin/package',,hash('%count', $import.importable, '%total', $import.entries|count))|wash}
        {if $import.importable|gt( $import.max )}<strong>{'At most %max are imported in this step; the rest stays for the next one.'|i18n('design/admin/package',,hash('%max', $import.max))|wash}</strong>{/if}
        {if $import.mode|eq('filter')}{'All changes of this filter: %count item(s) in all, taken %max at a time.'|i18n('design/admin/package',,hash('%count', $import.filter_total, '%max', $import.max))|wash}{/if}
    </p>
    {else}
    <h2 id="pcmp-import-title">{'Import from the package: result'|i18n('design/admin/package')}</h2>
    <p class="pcmp-import-lead">{'%done imported, %failed failed. The comparison below is up to date for them.'|i18n('design/admin/package',,hash('%done', $import.done, '%failed', $import.failed))|wash}</p>
    {/if}

    <form method="post" action={$compare.url_post|ezurl}>
    <ol class="pcmp-import-list">
    {foreach $import.entries as $entry}
        <li class="pcmp-import-entry{if is_set( $entry.result )} pcmp-result-{$entry.result|wash}{elseif $entry.importable|not} pcmp-result-skipped{/if}">
            <div class="pcmp-import-entry-head">
                <span class="pcmp-status pcmp-status-{$entry.status|wash}"><span class="pcmp-glyph" aria-hidden="true">{$glyphs[$entry.status]}</span> {$compare.status_labels[$entry.status]|wash}</span>
                <span class="pvf-kind pvf-kind-{$entry.kind|wash}">{if $entry.kind|eq('class')}{'Class'|i18n('design/admin/package')}{else}{'Object'|i18n('design/admin/package')}{/if}</span>
                <strong class="pcmp-import-name">{$entry.name|wash}</strong>
                {if $entry.class_identifier}<code>{$entry.class_identifier|wash}</code>{/if}
                {if is_set( $entry.result )}
                <span class="pcmp-result pcmp-result-badge-{$entry.result|wash}"><span aria-hidden="true">{$resultGlyphs[$entry.result]}</span> {$resultLabels[$entry.result]|wash}</span>
                {elseif $entry.importable|not}
                <span class="pcmp-result pcmp-result-badge-skipped"><span aria-hidden="true">–</span> {'Cannot be imported'|i18n('design/admin/package')}</span>
                {/if}
            </div>
            {if and( is_set( $entry.result ), $entry.result|ne('done') )}<p class="pcmp-import-reason">{$entry.message|wash}</p>
            {elseif $entry.importable|not}<p class="pcmp-import-reason">{$entry.reason|wash}</p>{/if}
            {if and( $entry.importable, $entry.changes|count|gt(0) )}
            <ul class="pcmp-import-changes">
                {foreach $entry.changes as $line}<li><span class="pcmp-glyph" aria-hidden="true">+</span> {$line|wash}</li>{/foreach}
            </ul>
            {/if}
            {if and( $entry.importable, $entry.kept|count|gt(0) )}
            <ul class="pcmp-import-kept">
                {foreach $entry.kept as $line}<li><span class="pcmp-glyph" aria-hidden="true">=</span> {$line|wash}</li>{/foreach}
            </ul>
            {/if}
            {if and( $import.step|eq('confirm'), $entry.importable )}<input type="hidden" name="ImportRemoteID[{$entry.index|wash}]" value="{$entry.remote_id|wash}" />{/if}
        </li>
    {/foreach}
    </ol>
    {if $import.step|eq('confirm')}
    {foreach $import.excluded as $value}<input type="hidden" name="ImportExcluded[]" value="{$value|wash}" />{/foreach}
    <input type="hidden" name="ImportMode" value="{$import.mode|wash}" />
    <div class="pcmp-import-actions">
        <input class="defaultbutton{if $import.importable|eq(0)} button-disabled{/if}" type="submit" name="ConfirmImportButton" value="{'Import %count item(s)'|i18n('design/admin/package',,hash('%count', min( $import.importable, $import.max )))|wash}"{if $import.importable|eq(0)} disabled="disabled"{/if} />
        <input class="button" type="submit" name="CancelImportButton" value="{'Cancel'|i18n('design/admin/package')}" />
    </div>
    {elseif and( $import.mode|eq('filter'), $import.remaining|gt(0) )}
    <div class="pcmp-import-actions">
        <input class="defaultbutton" type="submit" name="ImportFilterButton" value="{'Import the next ones (%count left in this filter)'|i18n('design/admin/package',,hash('%count', $import.remaining))|wash}" />
    </div>
    {/if}
    </form>
</section>
{undef $resultLabels $resultGlyphs}
