{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* package/compare/<name>: the package's content compared with the site's content tree and classes
   (kernel/package/compare.php, eZPackageComparison - kernel-only). A summary bar whose status chips
   are filters, a filter form, the paginated item list with sortable column headings and, for the
   item opened, a side by side (stacked on a narrow screen) word level difference per value: on the
   left what the site has, on the right what the package carries; removed text red, added text green.
   With the package install policy, items can be imported (eZPackageComparisonImport): the forms here
   only lead to a confirmation step (package/compare_import.tpl) that lists what will change.
   Every value from the package is escaped: packages are uploaded content. Every link is a path
   compare.php built, passed through |ezurl. The styles are in stylesheets/packagecompare.css. *}
{ezcss_require( 'packagecompare.css' )}
{def $glyphs = hash( 'new', '+', 'changed', '~', 'removed', '−', 'identical', '=', 'class_missing', '!' )
     $stateLabels = hash( 'changed', 'Changed'|i18n('design/admin/package'),
                          'package_only', 'Only in the package'|i18n('design/admin/package'),
                          'site_only', 'Only on the site'|i18n('design/admin/package'),
                          'identical', 'Identical'|i18n('design/admin/package') )
     $empty = 'Empty'|i18n('design/admin/package')}

<div class="context-block package-view-full package-compare">

{* DESIGN: Header START *}<div class="box-header"><div class="box-ml">
<h1 class="context-title">{'Compare %name with the site'|i18n('design/admin/package',,hash('%name', $package.name))|wash}</h1>
<p class="pvf-badges">
    <span class="pvf-badge pvf-badge-version" title="{'Version'|i18n('design/admin/package')}">{$package.version-number|wash}-{$package.release-number|wash}</span>
    {if $package.type}<span class="pvf-badge" title="{'Type'|i18n('design/admin/package')}">{$package.type|wash}</span>{/if}
    <span class="pvf-date">{"The package's classes and objects next to the site's own. Nothing on the site changes unless you import an item and confirm it."|i18n('design/admin/package')}</span>
</p>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <div class="pcmp-toolbar">
        <p class="pcmp-built">
            {'%count items compared (%classes classes, %objects objects) on %date in %seconds s.'|i18n('design/admin/package',,hash( '%count', $Compare.total_all, '%classes', $Compare.class_count, '%objects', $Compare.object_count, '%date', $Compare.built|l10n( shortdatetime ), '%seconds', $Compare.build_seconds ))|wash}
            {if $Compare.from_cache}<span class="pcmp-cached">{'Read from the cache; the site and the package are unchanged since.'|i18n('design/admin/package')}</span>{/if}
        </p>
        <form class="pcmp-toolbar-actions" method="post" action={$Compare.url_refresh|ezurl}>
            <input class="button" type="submit" name="CompareRefreshButton" value="{'Compare again'|i18n('design/admin/package')}" title="{'Build the comparison anew; takes a few seconds for a large package'|i18n('design/admin/package')}" />
            <a class="pvf-link-button" href={concat( 'package/view/full/', $package.name )|ezurl}>{'Back to the package'|i18n('design/admin/package')}</a>
        </form>
    </div>

    {if $Compare.import}
    {include uri='design:package/compare_import.tpl' compare=$Compare import=$Compare.import glyphs=$glyphs}
    {/if}

    {if $Compare.show_list}

    {* The summary bar: one chip per status with its count (over the class and search filters),
       a link that filters by it (or, when it is the filter already, clears it). Glyph and label
       tell the statuses apart without their colours. *}
    <nav class="pcmp-summary" aria-label="{'Filter by status'|i18n('design/admin/package')}">
        {foreach $Compare.chips as $chip}
        <a class="pcmp-chip{if $chip.status} pcmp-status-{$chip.status}{else} pcmp-chip-all{/if}{if $chip.active} pcmp-chip-active{/if}{if $chip.count|eq(0)} pcmp-chip-zero{/if}" href={$chip.url|ezurl}{if $chip.hint} title="{$chip.hint|wash}"{/if}{if $chip.active} aria-current="true"{/if}>
            {if $chip.status}<span class="pcmp-glyph" aria-hidden="true">{$glyphs[$chip.status]}</span>{/if}
            <span class="pcmp-chip-label">{$chip.label|wash}</span>
            <span class="pcmp-chip-count">{$chip.count|wash}</span>
        </a>
        {/foreach}
    </nav>

    <form class="pvf-filter pcmp-filter" method="get" action={$Compare.url_filter|ezurl}>
        <div class="pvf-field">
            <label for="compare-filter">{'Status'|i18n('design/admin/package')}</label>
            <select id="compare-filter" name="CompareFilter">
                <option value="">{'Any status'|i18n('design/admin/package')}</option>
                {foreach $Compare.status_labels as $status => $statusLabel}
                <option value="{$status|wash}"{if $Compare.filter|eq( $status )} selected{/if}>{$statusLabel|wash}</option>
                {/foreach}
            </select>
        </div>
        <div class="pvf-field">
            <label for="compare-class">{'Class'|i18n('design/admin/package')}</label>
            <select id="compare-class" name="CompareClass">
                <option value="">{'Any class'|i18n('design/admin/package')}</option>
                {foreach $Compare.classes as $classIdentifier => $classCount}
                <option value="{$classIdentifier|wash}"{if $Compare.class|eq( $classIdentifier )} selected{/if}>{$classIdentifier|wash} ({$classCount|wash})</option>
                {/foreach}
            </select>
        </div>
        <div class="pvf-field pvf-field-search">
            <label for="compare-search">{'Search name/remote ID'|i18n('design/admin/package')}</label>
            <input id="compare-search" type="search" name="CompareSearch" value="{$Compare.search|wash}" />
        </div>
        <div class="pvf-field">
            <label for="compare-limit">{'Per page'|i18n('design/admin/package')}</label>
            <select id="compare-limit" name="CompareLimit">
                {foreach array( '25', '50', '100', '250' ) as $limitChoice}
                <option value="{$limitChoice|wash}"{if $limitChoice|eq( $Compare.limit )} selected{/if}>{$limitChoice|wash}</option>
                {/foreach}
            </select>
        </div>
        <div class="pvf-field pvf-field-submit">
            <input class="defaultbutton" type="submit" name="CompareApply" value="{'Apply'|i18n('design/admin/package')}" />
            {if or( $Compare.filter, $Compare.class, $Compare.search )}
            <a class="pvf-reset" href={$Compare.url_filter|ezurl}>{'Clear filters'|i18n('design/admin/package')}</a>
            {/if}
        </div>
    </form>

    {if $Compare.viewed}
    {def $viewed = $Compare.viewed
         $detail = $Compare.detail}
    {* The opened item's own import form: its button, and a tick per value an import would set *}
    {if $viewed.offered}<form class="pcmp-viewer-form" method="post" action={$Compare.url_post|ezurl}>{/if}
    <section class="pcmp-viewer" aria-labelledby="pcmp-viewer-title">
        <div class="pcmp-viewer-head">
            <div class="pcmp-viewer-title">
                <span class="pcmp-status pcmp-status-{$viewed.status|wash}"><span class="pcmp-glyph" aria-hidden="true">{$glyphs[$viewed.status]}</span> {$Compare.status_labels[$viewed.status]|wash}</span>
                <span class="pvf-kind pvf-kind-{$viewed.kind|wash}">{if $viewed.kind|eq('class')}{'Class'|i18n('design/admin/package')}{else}{'Object'|i18n('design/admin/package')}{/if}</span>
                <h2 id="pcmp-viewer-title">{$viewed.name|wash}</h2>
                <p class="pcmp-viewer-ids">
                    {if $viewed.class_identifier}<span>{'Class'|i18n('design/admin/package')}: <code>{$viewed.class_identifier|wash}</code></span>{/if}
                    {if $viewed.remote_id}<span>{'Remote ID'|i18n('design/admin/package')}: <code>{$viewed.remote_id|wash}</code></span>{/if}
                    {if $viewed.summary}<span>{$viewed.summary|wash}</span>{/if}
                </p>
            </div>
            <div class="pvf-viewer-actions">
                {if and( $viewed.offered, $detail )}
                <input type="hidden" name="ImportViewedIndex" value="{$viewed.index|wash}" />
                <input class="defaultbutton" type="submit" name="ImportViewedButton" value="{'Import this item'|i18n('design/admin/package')}" title="{'Import what the package brings for this item; a confirmation follows'|i18n('design/admin/package')}" />
                {/if}
                {if $viewed.url_site}<a class="pvf-link-button" href={$viewed.url_site|ezurl}>{'Open on the site'|i18n('design/admin/package')}</a>{/if}
                {if $viewed.url_file}<a class="pvf-link-button" href={$viewed.url_file|ezurl}>{'Package file'|i18n('design/admin/package')}</a>{/if}
                <a class="pvf-link-button" href={$Compare.url_close|ezurl}>{'Close'|i18n('design/admin/package')}</a>
            </div>
        </div>
        <div class="pcmp-viewer-body">
        {if $detail|not}
            <p class="pvf-note">{'This item is no longer in the package or on the site. Compare again to bring the list up to date.'|i18n('design/admin/package')}</p>
        {else}
            {foreach $detail.notes as $note}<p class="pcmp-note">{$note|wash}</p>{/foreach}

            {if and( $detail.kind|eq('object'), or( $detail.site, $detail.package_info ) )}
            <dl class="pcmp-facts">
                {if $detail.site}
                <dt>{'On the site'|i18n('design/admin/package')}</dt>
                <dd>{'Object %id, modified %date'|i18n('design/admin/package',,hash('%id', $detail.site.id, '%date', $detail.site.modified|l10n( shortdatetime )))|wash}{if $detail.site.languages} &middot; {$detail.site.languages|implode( ', ' )|wash}{/if}</dd>
                {/if}
                {if $detail.package_info}
                <dt>{'In the package'|i18n('design/admin/package')}</dt>
                <dd>{if $detail.package_info.modified}{'Modified %date'|i18n('design/admin/package',,hash('%date', $detail.package_info.modified))|wash}{/if}{if $detail.package_info.languages} &middot; {$detail.package_info.languages|implode( ', ' )|wash}{/if}</dd>
                {/if}
            </dl>
            {/if}

            <p class="pcmp-legend"><span class="pcmp-legend-site">{'Left: the site'|i18n('design/admin/package')} &ndash; <del>{'text only the site has'|i18n('design/admin/package')}</del></span> <span class="pcmp-legend-package">{'Right: the package'|i18n('design/admin/package')} &ndash; <ins>{'text the package brings'|i18n('design/admin/package')}</ins></span></p>
            {if and( $viewed.offered, $viewed.kind|eq('object'), $viewed.status|eq('changed') )}
            <p class="pcmp-import-hint">{'Untick a value to keep what the site has when importing this item. Values only the site has are always kept.'|i18n('design/admin/package')}</p>
            {/if}

            {foreach $detail.sections as $section}
            <div class="pcmp-section">
                <h3 class="pcmp-section-title">
                    {if $section.language}<code>{$section.title|wash}</code>{else}{$section.title|wash}{/if}
                    {if $section.state|eq('package')}<span class="pcmp-state pcmp-state-package_only">{'Translation only in the package'|i18n('design/admin/package')}</span>
                    {elseif $section.state|eq('site')}<span class="pcmp-state pcmp-state-site_only">{'Translation only on the site'|i18n('design/admin/package')}</span>{/if}
                    <span class="pcmp-section-count">{'%differ differ, %same identical'|i18n('design/admin/package',,hash('%differ', $section.differing|count, '%same', $section.same|count))|wash}</span>
                </h3>

                {foreach $section.differing as $row}
                <div class="pcmp-row pcmp-row-{$row.state|wash}">
                    <div class="pcmp-row-head">
                        <strong class="pcmp-row-name">{$row.name|wash}</strong>
                        <code class="pcmp-row-identifier">{$row.identifier|wash}</code>
                        {if $row.datatype}<span class="pcmp-row-datatype">{$row.datatype|wash}</span>{/if}
                        <span class="pcmp-state pcmp-state-{$row.state|wash}">{$stateLabels[$row.state]|wash}</span>
                        {if $row.import_key}
                        <label class="pcmp-import-tick"{if $row.untickable|not} title="{'This value can only be imported together with the item'|i18n('design/admin/package')}"{/if}><input type="checkbox" name="ImportAttribute[]" value="{$row.import_key|wash}" checked="checked"{if $row.untickable|not} disabled="disabled"{/if} /> {'Import'|i18n('design/admin/package')}</label>
                        {if $row.untickable}<input type="hidden" name="ImportAttributeShown[]" value="{$row.import_key|wash}" />{/if}
                        {/if}
                    </div>
                    <div class="pcmp-sides">
                        <div class="pcmp-side pcmp-side-site">
                            <div class="pcmp-side-label">{'On the site'|i18n('design/admin/package')}</div>
                            {if $row.state|eq('package_only')}
                            <div class="pcmp-text pcmp-text-missing">{'Not on the site'|i18n('design/admin/package')}</div>
                            {elseif $row.state|eq('changed')}
                            <pre class="pcmp-text">{foreach $row.site_runs as $run}{if $run.op|eq('delete')}<del>{$run.text|wash}</del>{else}{$run.text|wash}{/if}{/foreach}{if $row.site_text|eq('')}<span class="pcmp-empty">{$empty|wash}</span>{/if}</pre>
                            {else}
                            <pre class="pcmp-text pcmp-text-removed">{if $row.site_text|eq('')}<span class="pcmp-empty">{$empty|wash}</span>{else}<del>{$row.site_text|wash}</del>{/if}</pre>
                            {/if}
                            {if $row.site_raw}<details class="pcmp-raw"><summary>{'XML on the site'|i18n('design/admin/package')}</summary><pre>{$row.site_raw|wash}</pre></details>{/if}
                        </div>
                        <div class="pcmp-side pcmp-side-package">
                            <div class="pcmp-side-label">{'In the package'|i18n('design/admin/package')}</div>
                            {if $row.state|eq('site_only')}
                            <div class="pcmp-text pcmp-text-missing">{'Not in the package'|i18n('design/admin/package')}</div>
                            {elseif $row.state|eq('changed')}
                            <pre class="pcmp-text">{foreach $row.package_runs as $run}{if $run.op|eq('insert')}<ins>{$run.text|wash}</ins>{else}{$run.text|wash}{/if}{/foreach}{if $row.package_text|eq('')}<span class="pcmp-empty">{$empty|wash}</span>{/if}</pre>
                            {else}
                            <pre class="pcmp-text pcmp-text-added">{if $row.package_text|eq('')}<span class="pcmp-empty">{$empty|wash}</span>{else}<ins>{$row.package_text|wash}</ins>{/if}</pre>
                            {/if}
                            {if $row.package_raw}<details class="pcmp-raw"><summary>{'XML in the package'|i18n('design/admin/package')}</summary><pre>{$row.package_raw|wash}</pre></details>{/if}
                        </div>
                    </div>
                    {foreach $row.notes as $note}<p class="pcmp-row-note">{$note|wash}</p>{/foreach}
                </div>
                {/foreach}

                {if $section.same|count|gt(0)}
                <details class="pcmp-same">
                    <summary>{'%count identical value(s)'|i18n('design/admin/package',,hash('%count', $section.same|count))|wash}</summary>
                    <table class="list pcmp-same-list">
                        <tbody>
                        {foreach $section.same as $row sequence array( 'bglight', 'bgdark' ) as $rowStyle}
                        <tr class="{$rowStyle}">
                            <th scope="row">{$row.name|wash} <code>{$row.identifier|wash}</code></th>
                            <td><pre class="pcmp-text pcmp-text-same">{if $row.package_text|eq('')}<span class="pcmp-empty">{$empty|wash}</span>{else}{$row.package_text|wash}{/if}</pre>
                            {foreach $row.notes as $note}<p class="pcmp-row-note">{$note|wash}</p>{/foreach}</td>
                        </tr>
                        {/foreach}
                        </tbody>
                    </table>
                </details>
                {/if}
            </div>
            {/foreach}

            {if $detail.placement}
            <div class="pcmp-section">
                <h3 class="pcmp-section-title">{'Placement'|i18n('design/admin/package')}
                    {if $detail.placement.changed}<span class="pcmp-state pcmp-state-changed">{'Changed'|i18n('design/admin/package')}</span>{/if}
                </h3>
                <div class="pcmp-sides">
                    <div class="pcmp-side pcmp-side-site">
                        <div class="pcmp-side-label">{'On the site'|i18n('design/admin/package')}</div>
                        <ul class="pcmp-places">
                        {foreach $detail.placement.site as $line}<li class="pcmp-place-{$line.state|wash}">{if $line.state|eq('removed')}<del>{$line.text|wash}</del>{else}{$line.text|wash}{/if}</li>{/foreach}
                        {if $detail.placement.site|count|eq(0)}<li class="pcmp-empty">{'Not on the site'|i18n('design/admin/package')}</li>{/if}
                        </ul>
                    </div>
                    <div class="pcmp-side pcmp-side-package">
                        <div class="pcmp-side-label">{'In the package'|i18n('design/admin/package')}</div>
                        <ul class="pcmp-places">
                        {foreach $detail.placement.package as $line}<li class="pcmp-place-{$line.state|wash}">{if $line.state|eq('added')}<ins>{$line.text|wash}</ins>{else}{$line.text|wash}{/if}</li>{/foreach}
                        {if $detail.placement.package|count|eq(0)}<li class="pcmp-empty">{'Not in the package'|i18n('design/admin/package')}</li>{/if}
                        </ul>
                    </div>
                </div>
                {if and( $viewed.offered, $detail.placement.changed )}<p class="pcmp-row-note">{'An import does not move existing locations; move the node in the content structure if its place should change.'|i18n('design/admin/package')}</p>{/if}
            </div>
            {/if}
        {/if}
        </div>
    </section>
    {if $viewed.offered}</form>{/if}
    {undef $viewed $detail}
    {/if}

    {if $Compare.pages|gt(1)}{include uri='design:package/view/contents_pager.tpl' browser=$Compare position='top' shown=$Compare.items|count noun='items'}{/if}

    {if $Compare.items|count|gt(0)}
    {* The list: one form for the row buttons and the selection; every button only leads to the confirmation *}
    {if $Compare.can_import}<form class="pcmp-list-form" method="post" action={$Compare.url_post|ezurl}>
    <div class="pcmp-bulk">
        <input class="button" type="submit" name="ImportSelectedButton" value="{'Import selected'|i18n('design/admin/package')}" />
        <input class="button{if $Compare.offered_in_filter|eq(0)} button-disabled{/if}" type="submit" name="ImportFilterButton" value="{'Import all changes of this filter (%count)'|i18n('design/admin/package',,hash('%count', $Compare.offered_in_filter))|wash}"{if $Compare.offered_in_filter|eq(0)} disabled="disabled"{/if} />
        <span class="pcmp-bulk-note">{'A confirmation lists what will change. At most %max items are imported per step; nothing only on the site is removed.'|i18n('design/admin/package',,hash('%max', $Compare.import_max))|wash}</span>
    </div>
    {/if}
    <div class="pvf-scroll">
    <table class="list pcmp-items">
        <thead><tr>
            {if $Compare.can_import}<th class="pcmp-col-select"><span class="pvf-hidden">{'Select'|i18n('design/admin/package')}</span></th>{/if}
            {include uri='design:parts/sortheader.tpl' key='status' label='Status'|i18n('design/admin/package') sort=$Compare.sort page_uri=$Compare.sort_uri cell_class='pcmp-col-status'}
            {include uri='design:parts/sortheader.tpl' key='name' label='Name'|i18n('design/admin/package') sort=$Compare.sort page_uri=$Compare.sort_uri cell_class='pcmp-col-name'}
            {include uri='design:parts/sortheader.tpl' key='class' label='Class'|i18n('design/admin/package') sort=$Compare.sort page_uri=$Compare.sort_uri cell_class='pcmp-col-class'}
            {include uri='design:parts/sortheader.tpl' key='differences' label='Differences'|i18n('design/admin/package') sort=$Compare.sort page_uri=$Compare.sort_uri cell_class='pcmp-col-summary'}
            <th class="pcmp-col-actions"><span class="pvf-hidden">{'Actions'|i18n('design/admin/package')}</span></th>
        </tr></thead>
        <tbody>
        {foreach $Compare.items as $item sequence array( 'bglight', 'bgdark' ) as $rowStyle}
        {def $isViewed = $Compare.viewed_index|eq( $item.index )}
        <tr class="{$rowStyle}{if $isViewed} pvf-current{/if}">
            {if $Compare.can_import}<td class="pcmp-col-select">{if $item.offered}<input type="checkbox" name="SelectedItems[]" value="{$item.index|wash}" aria-label="{'Select %name'|i18n('design/admin/package',,hash('%name', $item.name))|wash}" />{/if}</td>{/if}
            <td class="pcmp-col-status"><span class="pcmp-status pcmp-status-{$item.status|wash}"><span class="pcmp-glyph" aria-hidden="true">{$glyphs[$item.status]}</span> {$Compare.status_labels[$item.status]|wash}</span></td>
            <td class="pcmp-col-name">
                <span class="pcmp-item-name">{if $item.kind|eq('class')}<span class="pvf-kind pvf-kind-class">{'Class'|i18n('design/admin/package')}</span> {/if}{$item.name|wash}</span>
                <code class="pcmp-item-remote">{$item.remote_id|wash}</code>
            </td>
            <td class="pcmp-col-class"><code>{$item.class_identifier|wash}</code></td>
            <td class="pcmp-col-summary">{$item.summary|wash}</td>
            <td class="pcmp-col-actions">
                {if $item.offered}<button class="pvf-link-button pcmp-import-button" type="submit" name="ImportItemButton" value="{$item.index|wash}" title="{'Import what the package brings for this item; a confirmation follows'|i18n('design/admin/package')}">{'Import'|i18n('design/admin/package')}</button>{/if}
                {if $isViewed}
                <a class="pvf-link-button pvf-active" href={$Compare.url_close|ezurl} aria-current="true">{'Close'|i18n('design/admin/package')}</a>
                {else}
                <a class="pvf-link-button" href={$item.url_view|ezurl}>{'View'|i18n('design/admin/package')}</a>
                {/if}
            </td>
        </tr>
        {undef $isViewed}
        {/foreach}
        </tbody>
    </table>
    </div>
    {if $Compare.can_import}</form>{/if}

    {include uri='design:package/view/contents_pager.tpl' browser=$Compare position='bottom' shown=$Compare.items|count noun='items'}
    {else}
    <div class="pvf-empty-state">
        <p>{if $Compare.total_all|eq(0)}{'This package has no classes or objects to compare.'|i18n('design/admin/package')}{else}{'No item matches these filters.'|i18n('design/admin/package')}{/if}</p>
        {if or( $Compare.filter, $Compare.class, $Compare.search )}<p><a class="pvf-link-button" href={$Compare.url_filter|ezurl}>{'Clear filters'|i18n('design/admin/package')}</a></p>{/if}
    </div>
    {/if}

    {/if}

</div>

{* DESIGN: Content END *}</div></div></div>

</div>
{undef $glyphs $stateLabels $empty}
