{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* The pager of the package contents browser (package/view/full.tpl) and of the package comparison
   (package/compare.tpl), shown above and below their lists: which rows of how many are on this
   page, Page N of M, and First/Previous/Next/Last as links to the view parameter addresses the view
   built (url_first, ...), or as disabled labels where there is no such page.
   Parameters: browser - $ContentsBrowser or $Compare; position - 'top' or 'bottom';
   optional: shown - the number of rows on this page (default: the count of browser.files),
   noun - 'items' to count items rather than files. *}
{if is_set( $shown )}{def $pagerShown = $shown}{else}{def $pagerShown = $browser.files|count}{/if}
<div class="pvf-pager pvf-pager-{$position|wash}">
    <span class="pvf-pager-status">
        <strong>{'Page %page of %pages'|i18n('design/admin/package',,hash('%page', $browser.page, '%pages', $browser.pages))}</strong>
        {if $pagerShown|gt(0)}
        {if and( is_set( $noun ), $noun|eq( 'items' ) )}
        <span class="pvf-pager-range">{'Items %from–%to of %count'|i18n('design/admin/package',,hash('%from', $browser.offset|inc, '%to', sum( $browser.offset, $pagerShown ), '%count', $browser.total_filtered))}</span>
        {else}
        <span class="pvf-pager-range">{'Files %from–%to of %count'|i18n('design/admin/package',,hash('%from', $browser.offset|inc, '%to', sum( $browser.offset, $pagerShown ), '%count', $browser.total_filtered))}</span>
        {/if}
        {/if}
    </span>
    {if $browser.pages|gt(1)}
    <span class="pvf-pager-links">
    {if $browser.page|gt(1)}
        <a class="pvf-link-button" href={$browser.url_first|ezurl} title="{'First'|i18n('design/admin/package')}">&laquo;<span class="pvf-pager-label"> {'First'|i18n('design/admin/package')}</span></a>
        <a class="pvf-link-button" href={$browser.url_prev|ezurl} rel="prev" title="{'Previous'|i18n('design/admin/package')}">&lsaquo;<span class="pvf-pager-label"> {'Previous'|i18n('design/admin/package')}</span></a>
    {else}
        <span class="pvf-link-button pvf-disabled" aria-disabled="true">&laquo;<span class="pvf-pager-label"> {'First'|i18n('design/admin/package')}</span></span>
        <span class="pvf-link-button pvf-disabled" aria-disabled="true">&lsaquo;<span class="pvf-pager-label"> {'Previous'|i18n('design/admin/package')}</span></span>
    {/if}
    {if $browser.page|lt( $browser.pages )}
        <a class="pvf-link-button" href={$browser.url_next|ezurl} rel="next" title="{'Next'|i18n('design/admin/package')}"><span class="pvf-pager-label">{'Next'|i18n('design/admin/package')} </span>&rsaquo;</a>
        <a class="pvf-link-button" href={$browser.url_last|ezurl} title="{'Last'|i18n('design/admin/package')}"><span class="pvf-pager-label">{'Last'|i18n('design/admin/package')} </span>&raquo;</a>
    {else}
        <span class="pvf-link-button pvf-disabled" aria-disabled="true"><span class="pvf-pager-label">{'Next'|i18n('design/admin/package')} </span>&rsaquo;</span>
        <span class="pvf-link-button pvf-disabled" aria-disabled="true"><span class="pvf-pager-label">{'Last'|i18n('design/admin/package')} </span>&raquo;</span>
    {/if}
    </span>
    {/if}
</div>
{undef $pagerShown}
