{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let package=fetch( package,item,
                    hash( package_name, $package_name,
                          repository_id, $repository_id ) )}

<div class="context-block">

<div id="package" class="viewfull">
    <div id="pn-{$package.name|wash}" class="pt-{$package.type|wash}">


{* DESIGN: Header START *}<div class="box-header"><div class="box-ml">
<h1 class="context-title">
        {$package.name|wash}-{$package.version-number}-{$package.release-number}{if $package.release-timestamp}({$package.release-timestamp|l10n( shortdatetime )}){/if}{if $package.type|wash} [{$package.type}]{/if}
        - {if $package.install_type|eq( 'install' )}
            {if $package.is_installed}
                {'Installed'|i18n('design/admin/package')}
            {else}
                {'Not installed'|i18n('design/admin/package')}
            {/if}
        {else}
            {'Imported'|i18n('design/admin/package')}
        {/if}
</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <form method="post" action={concat( 'package/view/full/', $package.name )|ezurl}>

    <div class="object">

        <table>
        <tr>
        <td>

        <div class="summary">
            <label>{'Summary'|i18n('design/admin/package')}</label>
            <p>{$package.summary|wash}</p>
        </div>

        <div class="state">
            <label>{'State'|i18n('design/admin/package')}</label>
            <p>{$package.state|wash}</p>
        </div>

        <div class="licence">
            <label>{'License'|i18n('design/admin/package')}</label>
            <p>{$package.licence|wash}</p>
        </div>

        <div class="maintainers">
            <label>{'Maintainers'|i18n('design/admin/package')}</label>
            <p>
                {section var=maintainer loop=$package.maintainers}
                    <a href="mailto:{$maintainer.item.email}" subject="{"Regarding Exponential package '%packagename'"|i18n('design/admin/package',,hash( '%packagename', $package.name ) )}" title="{'Send email to the maintainer'|i18n('design/admin/package')}">{$maintainer.item.name|wash}</a> ({$maintainer.item.role|wash})
                {delimiter}, {/delimiter}
                {/section}
            </p>
        </div>

        <div class="description">
            <label>{'Description'|i18n('design/admin/package')}</label>
            <p>{$package.description}</p>
        </div>

        <div class="documents">
            <label>{'Documents'|i18n('design/admin/package')}</label>
            <p>
                {section var=document loop=$package.documents}
                {let document_path=$package|ezpackage( documentpath, $document.name )}
                    {if $document_path}<a href={$document_path|ezroot}>{/if}{$document.name|wash}{if $document_path}</a>{/if}
                {/let}
                {delimiter}, {/delimiter}
                {/section}
            </p>
        </div>

        <div class="changelog">
            <label>{'Changelog'|i18n('design/admin/package')}</label>
            <p>
                {section var=log loop=$package.changelog}
                    <h3><p class="byline"><em class="date">({$log.item.timestamp|l10n( shortdatetime )})</em> <a href="mailto:{$log.item.email}" subject="{"Regarding Exponential package '%packagename'"|i18n('design/admin/package',,hash( '%packagename', $package.name ) )}" title="{'Send email to the maintainer'|i18n('design/admin/package')}">{$log.item.person|wash}</a></p></h3>
                    <ul>
                    {section var=change loop=$log.item.changes}
                    <li>
                        {$change.item|wash}
                    </li>
                    {/section}
                    </ul>
                {delimiter}<hr/> {/delimiter}
                {/section}
            </p>
        </div>

        </td>

        <td valign="top">
            {let thumbnail_list=$package.thumbnail-list}
            {if $thumbnail_list}
            <div class="thumbnail">
                <img src={concat( $package|ezpackage( fileitempath, $thumbnail_list[0] ) )|ezroot} alt="{$thumbnail_list[0].name|wash}" />
            </div>
            {/if}
            {/let}
        </td>

        </tr>
        </table>

    </div>

    <div class="links">
        {if $package.file-count|gt( 0 )}
        <p>[ <a href={concat( "package/view/files/", $package.name )|ezurl}>{'File list'|i18n('design/admin/package')}</a> ]</p>
        {/if}
    </div>

    </div>
    {* DESIGN: Content END *}</div></div></div>

    <div class="controlbar">
    {* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml">


    {if $package.can_export}
    <div class="block">
        {if $package.install_type|eq( 'install' )}
            {if $package.is_installed}
                <input class="button" type="submit" name="UninstallButton" value="{'Uninstall'|i18n( 'design/admin/package')}" />
                <input class="button" type="submit" name="InstallButton" value="{'Reinstall'|i18n( 'design/admin/package')}" />
            {else}
                <input class="button" type="submit" name="InstallButton" value="{'Install'|i18n( 'design/admin/package')}" />
            {/if}
        {/if}
        <input class="button" type="submit" name="ExportButton" value="{'Export to file'|i18n( 'design/admin/package')}" />
    </div>
    {/if}

    </form>

    {if $ContentsBrowser}
    {* The package contents browser: every file the package carries, paginated and filtered
       (kernel/package/view.php, eZPackageFileBrowser - no dependency on any extension). Its own
       form for the type/search/per-page filter (independent of the export/install one above);
       pagination and "View" are plain links to the same view with its state in view parameters,
       (type)/(search)/(limit)/(offset)/(file), each path built by kernel/package/view.php
       (url_first/url_prev/... , and url_view per file). The form still submits GET fields; the
       view answers them with one redirect to the view-parameter address. Nothing here writes. *}
    {def $browseBaseURL = concat( 'package/view/full/', $package.name )|ezurl}
    <div class="contents-browser">
        <h2>{'Package contents'|i18n('design/admin/package')}</h2>
        <p>{'%shown of %total files'|i18n('design/admin/package',,hash('%shown', $ContentsBrowser.total_filtered, '%total', $ContentsBrowser.total_all))}</p>

        <form method="get" action={$browseBaseURL}>
        <table class="filter">
            <tr>
                <td>
                    <label for="browse-type">{'Type'|i18n('design/admin/package')}</label>
                    <select id="browse-type" name="BrowseType">
                        <option value="">{'Any type'|i18n('design/admin/package')}</option>
                        <option value="class"{if $ContentsBrowser.type_filter|eq('class')} selected{/if}>{'Content class'|i18n('design/admin/package')}</option>
                        <option value="object"{if $ContentsBrowser.type_filter|eq('object')} selected{/if}>{'Content object'|i18n('design/admin/package')}</option>
                        <option value="image"{if $ContentsBrowser.type_filter|eq('image')} selected{/if}>{'Image'|i18n('design/admin/package')}</option>
                        <option value="simplefile"{if $ContentsBrowser.type_filter|eq('simplefile')} selected{/if}>{'File'|i18n('design/admin/package')}</option>
                        <option value="document"{if $ContentsBrowser.type_filter|eq('document')} selected{/if}>{'Document'|i18n('design/admin/package')}</option>
                        <option value="package"{if $ContentsBrowser.type_filter|eq('package')} selected{/if}>{'Package definition'|i18n('design/admin/package')}</option>
                        <option value="other"{if $ContentsBrowser.type_filter|eq('other')} selected{/if}>{'Other'|i18n('design/admin/package')}</option>
                    </select>
                </td>
                <td>
                    <label for="browse-search">{'Search path/name'|i18n('design/admin/package')}</label>
                    <input id="browse-search" type="text" name="BrowseSearch" value="{$ContentsBrowser.search|wash}" />
                </td>
                <td>
                    <label for="browse-limit">{'Per page'|i18n('design/admin/package')}</label>
                    <select id="browse-limit" name="BrowseLimit">
                        {foreach array( '25', '50', '100', '250', '1000', 'all' ) as $limitChoice}
                        <option value="{$limitChoice|wash}"{if $limitChoice|eq( $ContentsBrowser.limit )} selected{/if}>{cond( $limitChoice|eq('all'), 'All'|i18n('design/admin/package'), $limitChoice|wash )}</option>
                        {/foreach}
                    </select>
                </td>
                <td><input class="button" type="submit" name="BrowseApply" value="{'Apply'|i18n('design/admin/package')}" /></td>
            </tr>
        </table>
        </form>

        {if $ContentsBrowser.viewed_file}
        <div class="contents-browser-viewer">
            <h3><code>{$ContentsBrowser.viewed_file.path|wash}</code></h3>
            <p>{$ContentsBrowser.viewed_file.kind|wash} &middot; {$ContentsBrowser.viewed_file.size} B</p>
            {if $ContentsBrowser.viewed_object}
            <table>
                <tr><th>{'Name'|i18n('design/admin/package')}</th><td>{$ContentsBrowser.viewed_object.name|wash}</td></tr>
                <tr><th>{'Class'|i18n('design/admin/package')}</th><td><code>{$ContentsBrowser.viewed_object.class_identifier|wash}</code></td></tr>
                <tr><th>{'Remote ID'|i18n('design/admin/package')}</th><td>{$ContentsBrowser.viewed_object.remote_id|wash}</td></tr>
            </table>
            {foreach $ContentsBrowser.viewed_object.translations as $language => $attributes}
            <h4>{$language|wash}</h4>
            <table>
                <thead><tr><th>{'Attribute'|i18n('design/admin/package')}</th><th>{'Datatype'|i18n('design/admin/package')}</th><th>{'Value'|i18n('design/admin/package')}</th></tr></thead>
                <tbody>
                {foreach $attributes as $identifier => $attribute}
                <tr><td><code>{$identifier|wash}</code></td><td>{$attribute.type|wash}</td><td>{$attribute.text|wash}</td></tr>
                {/foreach}
                </tbody>
            </table>
            {/foreach}
            {if $ContentsBrowser.viewed_object.more_objects|gt(0)}
            <p>{'+ %count more object(s) in the same file'|i18n('design/admin/package',,hash('%count', $ContentsBrowser.viewed_object.more_objects))}</p>
            {/if}
            {elseif $ContentsBrowser.viewed_file.kind|eq('image')}
            <p><img src={concat( 'package/viewfile/', $package.name, '/', $ContentsBrowser.viewed_file.index )|ezurl} alt="{$ContentsBrowser.viewed_file.path|wash}" /></p>
            {else}
            <pre>{$ContentsBrowser.viewed_content|wash}</pre>
            {/if}
            <p><a class="button" href={$ContentsBrowser.url_close|ezurl}>{'Close'|i18n('design/admin/package')}</a></p>
        </div>
        {/if}

        <table>
            <thead><tr><th>{'Path'|i18n('design/admin/package')}</th><th>{'Type'|i18n('design/admin/package')}</th><th>{'Size'|i18n('design/admin/package')}</th><th></th></tr></thead>
            <tbody>
            {foreach $ContentsBrowser.files as $file}
            <tr>
                <td><code>{$file.path|wash}</code></td>
                <td>{$file.kind|wash}</td>
                <td>{$file.size} B</td>
                <td>
                    {if $file.kind|ne('other')}
                    <a class="button" href={$file.url_view|ezurl}>{'View'|i18n('design/admin/package')}</a>
                    {/if}
                    <a href={concat( 'package/viewfile/', $package.name, '/', $file.index )|ezurl} target="_blank" rel="noopener">{'Download'|i18n('design/admin/package')}</a>
                </td>
            </tr>
            {/foreach}
            {if $ContentsBrowser.files|count|eq(0)}
            <tr><td colspan="4">{'No file matches these filters.'|i18n('design/admin/package')}</td></tr>
            {/if}
            </tbody>
        </table>

        <p>
            {'Page %page of %pages'|i18n('design/admin/package',,hash('%page', $ContentsBrowser.page, '%pages', $ContentsBrowser.pages))}
            {if $ContentsBrowser.page|gt(1)}
            <a class="button" href={$ContentsBrowser.url_first|ezurl}>{'First'|i18n('design/admin/package')}</a>
            <a class="button" href={$ContentsBrowser.url_prev|ezurl}>{'Previous'|i18n('design/admin/package')}</a>
            {/if}
            {if $ContentsBrowser.page|lt( $ContentsBrowser.pages )}
            <a class="button" href={$ContentsBrowser.url_next|ezurl}>{'Next'|i18n('design/admin/package')}</a>
            <a class="button" href={$ContentsBrowser.url_last|ezurl}>{'Last'|i18n('design/admin/package')}</a>
            {/if}
        </p>
    </div>
    {undef $browseBaseURL}
    {/if}

    </div>
    {* DESIGN: Control bar END *}</div></div>


    </div>
</div>

</div>

{/let}
