{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let package=fetch( package,item,
                    hash( package_name, $package_name,
                          repository_id, $repository_id ) )}
{* The labels of the kinds eZPackageFileBrowser tells files apart by, shared by the filter, the
   file list's type badges and the viewed file's header. *}
{def $kindLabels = hash( 'class', 'Content class'|i18n('design/admin/package'),
                         'object', 'Content object'|i18n('design/admin/package'),
                         'image', 'Image'|i18n('design/admin/package'),
                         'simplefile', 'File'|i18n('design/admin/package'),
                         'document', 'Document'|i18n('design/admin/package'),
                         'package', 'Package definition'|i18n('design/admin/package'),
                         'other', 'Other'|i18n('design/admin/package') )
     $kindShortLabels = hash( 'class', 'Class'|i18n('design/admin/package'),
                              'object', 'Object'|i18n('design/admin/package'),
                              'image', 'Image'|i18n('design/admin/package'),
                              'simplefile', 'File'|i18n('design/admin/package'),
                              'document', 'Document'|i18n('design/admin/package'),
                              'package', 'Package'|i18n('design/admin/package'),
                              'other', 'Other'|i18n('design/admin/package') )}

<div class="context-block package-view-full">

<div id="package" class="viewfull">
    <div id="pn-{$package.name|wash}" class="pt-{$package.type|wash}">

{* DESIGN: Header START *}<div class="box-header"><div class="box-ml">
<h1 class="context-title">{$package.name|wash}</h1>
<p class="pvf-badges">
    <span class="pvf-badge pvf-badge-version" title="{'Version'|i18n('design/admin/package')}">{$package.version-number|wash}-{$package.release-number|wash}</span>
    {if $package.type}<span class="pvf-badge" title="{'Type'|i18n('design/admin/package')}">{$package.type|wash}</span>{/if}
    {if $package.install_type|eq( 'install' )}
        {if $package.is_installed}
            <span class="pvf-badge pvf-badge-ok">{'Installed'|i18n('design/admin/package')}</span>
        {else}
            <span class="pvf-badge pvf-badge-muted">{'Not installed'|i18n('design/admin/package')}</span>
        {/if}
    {else}
        <span class="pvf-badge pvf-badge-info">{'Imported'|i18n('design/admin/package')}</span>
    {/if}
    {if $package.release-timestamp}<span class="pvf-date">{'Released %date'|i18n('design/admin/package',,hash( '%date', $package.release-timestamp|l10n( shortdatetime ) ))}</span>{/if}
</p>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    <form method="post" action={concat( 'package/view/full/', $package.name )|ezurl}>

    <div class="pvf-overview">
        <dl class="pvf-meta">
            <dt>{'Summary'|i18n('design/admin/package')}</dt>
            <dd>{$package.summary|wash}</dd>

            <dt>{'State'|i18n('design/admin/package')}</dt>
            <dd>{$package.state|wash}</dd>

            <dt>{'License'|i18n('design/admin/package')}</dt>
            <dd>{$package.licence|wash}</dd>

            <dt>{'Maintainers'|i18n('design/admin/package')}</dt>
            <dd>
                {section var=maintainer loop=$package.maintainers}
                    <a href="mailto:{$maintainer.item.email|wash}" title="{'Send email to the maintainer'|i18n('design/admin/package')}">{$maintainer.item.name|wash}</a> ({$maintainer.item.role|wash})
                {delimiter}, {/delimiter}
                {/section}
            </dd>

            <dt>{'Documents'|i18n('design/admin/package')}</dt>
            <dd>
                {section var=document loop=$package.documents}
                {let document_path=$package|ezpackage( documentpath, $document.name )}
                    {if $document_path}<a href={$document_path|ezroot}>{/if}{$document.name|wash}{if $document_path}</a>{/if}
                {/let}
                {delimiter}, {/delimiter}
                {/section}
                {if $package.file-count|gt( 0 )}
                    <a class="pvf-filelist-link" href={concat( "package/view/files/", $package.name )|ezurl}>{'File list'|i18n('design/admin/package')}</a>
                {/if}
            </dd>

            <dt>{'Description'|i18n('design/admin/package')}</dt>
            <dd>{$package.description}</dd>
        </dl>

        {let thumbnail_list=$package.thumbnail-list}
        {if $thumbnail_list}
        <div class="pvf-thumbnail">
            <img src={concat( $package|ezpackage( fileitempath, $thumbnail_list[0] ) )|ezroot} alt="{$thumbnail_list[0].name|wash}" />
        </div>
        {/if}
        {/let}
    </div>

    {if $package.changelog}
    <div class="pvf-changelog">
        <h2>{'Changelog'|i18n('design/admin/package')}</h2>
        {section var=log loop=$package.changelog}
        <div class="pvf-changelog-entry">
            <p class="pvf-changelog-byline"><span class="pvf-date">{$log.item.timestamp|l10n( shortdatetime )}</span> <a href="mailto:{$log.item.email|wash}" title="{'Send email to the maintainer'|i18n('design/admin/package')}">{$log.item.person|wash}</a></p>
            <ul>
            {section var=change loop=$log.item.changes}
                <li>{$change.item|wash}</li>
            {/section}
            </ul>
        </div>
        {/section}
    </div>
    {/if}

    {if $package.can_export}
    <div class="pvf-actions">
        {if $package.install_type|eq( 'install' )}
            {if $package.is_installed}
                <input class="button" type="submit" name="InstallButton" value="{'Reinstall'|i18n( 'design/admin/package')}" />
                <input class="defaultbutton" type="submit" name="ExportButton" value="{'Export to file'|i18n( 'design/admin/package')}" />
                <input class="button pvf-button-danger" type="submit" name="UninstallButton" value="{'Uninstall'|i18n( 'design/admin/package')}" />
            {else}
                <input class="defaultbutton" type="submit" name="InstallButton" value="{'Install'|i18n( 'design/admin/package')}" />
                <input class="button" type="submit" name="ExportButton" value="{'Export to file'|i18n( 'design/admin/package')}" />
            {/if}
        {else}
            <input class="defaultbutton" type="submit" name="ExportButton" value="{'Export to file'|i18n( 'design/admin/package')}" />
        {/if}
    </div>
    {/if}

    </form>

    {if $ContentsBrowser}
    {* The package contents browser: every file the package carries, paginated and filtered
       (kernel/package/view.php, eZPackageFileBrowser - no dependency on any extension). Its own
       form for the type/search/per-page filter (independent of the export/install one above);
       pagination and "View" are plain links to the same view with its state in view parameters,
       (type)/(search)/(limit)/(offset)/(file), each path built by kernel/package/view.php
       (url_first/url_prev/... , and url_view per file). The form still submits GET fields; the
       view answers them with one redirect to the view-parameter address. Nothing here writes. *}
    {def $browseBaseURL = concat( 'package/view/full/', $package.name )|ezurl
         $viewedIndex = -1}
    {if $ContentsBrowser.viewed_file}{set $viewedIndex = $ContentsBrowser.viewed_file.index}{/if}
    <div class="pvf-browser">
        <div class="pvf-browser-head">
            <h2>{'Package contents'|i18n('design/admin/package')}</h2>
            <span class="pvf-count">{'%shown of %total files'|i18n('design/admin/package',,hash('%shown', $ContentsBrowser.total_filtered, '%total', $ContentsBrowser.total_all))}</span>
        </div>

        <form class="pvf-filter" method="get" action={$browseBaseURL}>
            <div class="pvf-field">
                <label for="browse-type">{'Type'|i18n('design/admin/package')}</label>
                <select id="browse-type" name="BrowseType">
                    <option value="">{'Any type'|i18n('design/admin/package')}</option>
                    {foreach $kindLabels as $kind => $kindLabel}
                    <option value="{$kind|wash}"{if $ContentsBrowser.type_filter|eq( $kind )} selected{/if}>{$kindLabel|wash}</option>
                    {/foreach}
                </select>
            </div>
            <div class="pvf-field pvf-field-search">
                <label for="browse-search">{'Search path/name'|i18n('design/admin/package')}</label>
                <input id="browse-search" type="search" name="BrowseSearch" value="{$ContentsBrowser.search|wash}" />
            </div>
            <div class="pvf-field">
                <label for="browse-limit">{'Per page'|i18n('design/admin/package')}</label>
                <select id="browse-limit" name="BrowseLimit">
                    {foreach array( '25', '50', '100', '250', '1000', 'all' ) as $limitChoice}
                    <option value="{$limitChoice|wash}"{if $limitChoice|eq( $ContentsBrowser.limit )} selected{/if}>{cond( $limitChoice|eq('all'), 'All'|i18n('design/admin/package'), $limitChoice|wash )}</option>
                    {/foreach}
                </select>
            </div>
            <div class="pvf-field pvf-field-submit">
                <input class="defaultbutton" type="submit" name="BrowseApply" value="{'Apply'|i18n('design/admin/package')}" />
                {if or( $ContentsBrowser.type_filter, $ContentsBrowser.search )}
                <a class="pvf-reset" href={$browseBaseURL}>{'Clear filters'|i18n('design/admin/package')}</a>
                {/if}
            </div>
        </form>

        {if $ContentsBrowser.viewed_file}
        {def $viewed = $ContentsBrowser.viewed_file}
        <div class="pvf-viewer">
            <div class="pvf-viewer-head">
                <div class="pvf-viewer-title">
                    <code class="pvf-path">{$viewed.path|wash}</code>
                    <span class="pvf-viewer-meta">
                        <span class="pvf-kind pvf-kind-{$viewed.kind|wash}">{cond( is_set( $kindLabels[$viewed.kind] ), $kindLabels[$viewed.kind], $viewed.kind )|wash}</span>
                        <span class="pvf-size" title="{$viewed.size|wash} B">{$viewed.size|si( byte )}</span>
                    </span>
                </div>
                <div class="pvf-viewer-actions">
                    <a class="pvf-link-button" href={concat( 'package/viewfile/', $package.name, '/', $viewed.index )|ezurl} target="_blank" rel="noopener">{'Download'|i18n('design/admin/package')}</a>
                    <a class="pvf-link-button" href={$ContentsBrowser.url_close|ezurl}>{'Close'|i18n('design/admin/package')}</a>
                </div>
            </div>
            <div class="pvf-viewer-body">
            {if $ContentsBrowser.viewed_object}
                <table class="list pvf-object">
                    <tr><th scope="row">{'Name'|i18n('design/admin/package')}</th><td>{$ContentsBrowser.viewed_object.name|wash}</td></tr>
                    <tr><th scope="row">{'Class'|i18n('design/admin/package')}</th><td><code>{$ContentsBrowser.viewed_object.class_identifier|wash}</code></td></tr>
                    <tr><th scope="row">{'Remote ID'|i18n('design/admin/package')}</th><td><code>{$ContentsBrowser.viewed_object.remote_id|wash}</code></td></tr>
                </table>
                {foreach $ContentsBrowser.viewed_object.translations as $language => $attributes}
                <h3 class="pvf-language">{$language|wash}</h3>
                <div class="pvf-scroll">
                <table class="list pvf-attributes">
                    <thead><tr><th>{'Attribute'|i18n('design/admin/package')}</th><th>{'Datatype'|i18n('design/admin/package')}</th><th>{'Value'|i18n('design/admin/package')}</th></tr></thead>
                    <tbody>
                    {foreach $attributes as $identifier => $attribute sequence array( 'bglight', 'bgdark' ) as $rowStyle}
                    <tr class="{$rowStyle}"><td><code>{$identifier|wash}</code></td><td>{$attribute.type|wash}</td><td class="pvf-value">{$attribute.text|wash}</td></tr>
                    {/foreach}
                    </tbody>
                </table>
                </div>
                {/foreach}
                {if $ContentsBrowser.viewed_object.more_objects|gt(0)}
                <p class="pvf-note">{'+ %count more object(s) in the same file'|i18n('design/admin/package',,hash('%count', $ContentsBrowser.viewed_object.more_objects))}</p>
                {/if}
            {elseif $viewed.kind|eq('image')}
                <div class="pvf-image"><img src={concat( 'package/viewfile/', $package.name, '/', $viewed.index )|ezurl} alt="{$viewed.path|wash}" /></div>
            {else}
                <pre class="pvf-code">{$ContentsBrowser.viewed_content|wash}</pre>
            {/if}
            </div>
        </div>
        {undef $viewed}
        {/if}

        {include uri='design:package/view/contents_pager.tpl' browser=$ContentsBrowser position='top'}

        <div class="pvf-scroll">
        <table class="list pvf-files">
            <thead><tr>
                <th class="pvf-col-path">{'Path'|i18n('design/admin/package')}</th>
                <th class="pvf-col-type">{'Type'|i18n('design/admin/package')}</th>
                <th class="pvf-col-size">{'Size'|i18n('design/admin/package')}</th>
                <th class="pvf-col-actions"><span class="pvf-hidden">{'Actions'|i18n('design/admin/package')}</span></th>
            </tr></thead>
            <tbody>
            {foreach $ContentsBrowser.files as $file sequence array( 'bglight', 'bgdark' ) as $rowStyle}
            <tr class="{$rowStyle}{if $file.index|eq( $viewedIndex )} pvf-current{/if}">
                {def $pathParts = $file.path|explode( '/' )}
                <td class="pvf-col-path"><code>{if $pathParts|count|gt(1)}<span class="pvf-dir">{$pathParts|extract_left( $pathParts|count|dec )|implode( '/' )|wash}/</span>{/if}<span class="pvf-name">{$pathParts|extract_right( 1 )|implode( '' )|wash}</span></code></td>
                {undef $pathParts}
                <td class="pvf-col-type"><span class="pvf-kind pvf-kind-{$file.kind|wash}" title="{cond( is_set( $kindLabels[$file.kind] ), $kindLabels[$file.kind], $file.kind )|wash}">{cond( is_set( $kindShortLabels[$file.kind] ), $kindShortLabels[$file.kind], $file.kind )|wash}</span></td>
                <td class="pvf-col-size" title="{$file.size|wash} B">{$file.size|si( byte )}</td>
                <td class="pvf-col-actions">
                    {if $file.kind|ne('other')}
                    {if $file.index|eq( $viewedIndex )}
                    <a class="pvf-link-button pvf-active" href={$ContentsBrowser.url_close|ezurl} aria-current="true">{'Close'|i18n('design/admin/package')}</a>
                    {else}
                    <a class="pvf-link-button" href={$file.url_view|ezurl}>{'View'|i18n('design/admin/package')}</a>
                    {/if}
                    {/if}
                    <a class="pvf-link-button" href={concat( 'package/viewfile/', $package.name, '/', $file.index )|ezurl} target="_blank" rel="noopener" title="{'Download'|i18n('design/admin/package')}">{'Download'|i18n('design/admin/package')}</a>
                </td>
            </tr>
            {/foreach}
            {if $ContentsBrowser.files|count|eq(0)}
            <tr class="bglight"><td colspan="4" class="pvf-empty">{'No file matches these filters.'|i18n('design/admin/package')}</td></tr>
            {/if}
            </tbody>
        </table>
        </div>

        {include uri='design:package/view/contents_pager.tpl' browser=$ContentsBrowser position='bottom'}
    </div>
    {undef $browseBaseURL $viewedIndex}
    {/if}

</div>

{* DESIGN: Content END *}</div></div></div>

    </div>
</div>

</div>
{undef $kindLabels $kindShortLabels}

{/let}
