<?php
/**
 * How the REST router picks a route (doc/guides/api-keys.md, "Routes of the ezp provider").
 *
 *  RM-01 a route that matches the path but not the method no longer ends the search: the next route is tried
 *  RM-02 405 only when no route takes the method; Allow lists the methods of every route that matched the path
 *  RM-03 no route for the path: 404 (ezcMvcRouteNotFoundException)
 *  RM-04 a versioned route takes one version or a list; it answers only for those
 *  RM-05 a URL generated by a route answering for several versions keeps the version of the current request
 *  RM-06 a route kept in the route cache before the list existed still answers for its one version
 *  RM-07 the authentication and error routes answer every method (a refused POST gets its 401/403, not 405)
 *  RM-08 the ezp provider of ezprestapi: reads at v1 and v2, create/update/delete at v2 with POST (delete with DELETE too)
 *
 * No database: the routes are built in memory and the prefix filter's static state is set by the test and put back.
 *
 * @copyright Copyright (C) 1998 - 2026 7x & Exponential Foundation. All rights reserved.
 * @license GNU General Public License v2.0 (or any later version)
 * @package tests
 * @group kernel
 * @group rest
 */

class ezpRestRouteMatchingTestRouter extends ezpRestRouter
{
    public $testRoutes = array();

    public function createRoutes()
    {
        return $this->testRoutes;
    }
}

class ezpRestRouteMatchingTest extends PHPUnit\Framework\TestCase
{
    private $statics = array();

    protected function setUp(): void
    {
        if ( !class_exists( 'ezcMvcRequest' ) )
            $this->markTestSkipped( 'the MVC component of the Zeta Components is not installed' );
        chdir( dirname( __DIR__, 5 ) );
        foreach ( array( 'version', 'apiProvider', 'apiPrefix' ) as $name )
        {
            $property = new ReflectionProperty( 'ezpRestPrefixFilterInterface', $name );
            $this->statics[] = array( $property, $property->getValue() );
        }
        $this->version( 2 );
    }

    protected function tearDown(): void
    {
        foreach ( $this->statics as $static )
            $static[0]->setValue( null, $static[1] );
        $this->statics = array();
    }

    private function version( $version, $provider = 'ezp', $prefix = '/api' )
    {
        ( new ReflectionProperty( 'ezpRestPrefixFilterInterface', 'version' ) )->setValue( null, $version );
        ( new ReflectionProperty( 'ezpRestPrefixFilterInterface', 'apiProvider' ) )->setValue( null, $provider );
        ( new ReflectionProperty( 'ezpRestPrefixFilterInterface', 'apiPrefix' ) )->setValue( null, $prefix );
    }

    private static function request( $method, $uri )
    {
        $request = new ezpRestRequest();
        $request->uri = $uri;
        $request->protocol = 'http-' . strtolower( $method );
        return $request;
    }

    /**
     * The controller::action the routes pick for the request, or 405 (with the Allow list) or 404.
     */
    private static function pick( array $routes, $method, $uri )
    {
        $router = new ezpRestRouteMatchingTestRouter( self::request( $method, $uri ) );
        $router->testRoutes = $routes;
        try
        {
            $info = $router->getRoutingInformation();
            return $info->controllerClass . '::' . $info->action;
        }
        catch ( ezpRouteMethodNotAllowedException $e )
        {
            $allowed = $e->getAllowedMethods();
            sort( $allowed );
            return '405 ' . implode( ',', $allowed );
        }
        catch ( ezcMvcRouteNotFoundException $e )
        {
            return '404';
        }
    }

    private static function readAndWrite( $writeFirst )
    {
        $read = new ezpMvcRailsRoute( '/content/node/:nodeId', 'K1Controller', array( 'http-get' => 'view' ) );
        $write = new ezpMvcRailsRoute( '/content/node/:nodeId', 'K1Controller', array( 'http-post' => 'update' ) );
        $create = new ezpMvcRailsRoute( '/content/node/create', 'K1Controller', array( 'http-post' => 'create' ) );
        return $writeFirst ? array( 'u' => $write, 'c' => $create, 'r' => $read ) : array( 'r' => $read, 'u' => $write, 'c' => $create );
    }

    /** RM-01 */
    public function testNextRouteIsTriedWhenTheMethodDoesNotFit()
    {
        foreach ( array( false, true ) as $writeFirst )
        {
            $routes = self::readAndWrite( $writeFirst );
            $this->assertSame( 'K1Controller::view', self::pick( $routes, 'GET', '/content/node/5' ) );
            $this->assertSame( 'K1Controller::update', self::pick( $routes, 'POST', '/content/node/5' ) );
        }
        // the general pattern first: /content/node/:nodeId matches "create" too, the POST still reaches create
        $routes = array( 'r' => new ezpMvcRailsRoute( '/content/node/:nodeId', 'K1Controller', array( 'http-get' => 'view' ) ),
                         'c' => new ezpMvcRailsRoute( '/content/node/create', 'K1Controller', array( 'http-post' => 'create' ) ) );
        $this->assertSame( 'K1Controller::create', self::pick( $routes, 'POST', '/content/node/create' ) );
        $regexp = array( 'l' => new ezpMvcRegexpRoute( '@^/content/node/(?P<nodeId>\d+)/list$@', 'K1Controller', array( 'http-get' => 'list' ) ),
                         'p' => new ezpMvcRailsRoute( '/content/node/:nodeId/list', 'K1Controller', array( 'http-post' => 'sort' ) ) );
        $this->assertSame( 'K1Controller::sort', self::pick( $regexp, 'POST', '/content/node/7/list' ), 'regular expression routes too' );
    }

    /** RM-02, RM-03 */
    public function testMethodNotAllowedAndNotFound()
    {
        $routes = self::readAndWrite( false );
        $this->assertSame( '405 GET,OPTIONS,POST', self::pick( $routes, 'DELETE', '/content/node/5' ), 'the methods of both routes' );
        $this->assertSame( '404', self::pick( $routes, 'GET', '/content/object/5' ) );
        $this->assertSame( 'K1Controller::httpOptions', self::pick( $routes, 'OPTIONS', '/content/node/5' ) );
    }

    /** RM-04 */
    public function testVersionedRouteTakesOneVersionOrAList()
    {
        $inner = new ezpMvcRailsRoute( '/content/node/:nodeId', 'K1Controller', array( 'http-get' => 'view' ) );
        $both = new ezpRestVersionedRoute( $inner, array( 1, 2 ) );
        $two = new ezpRestVersionedRoute( new ezpMvcRailsRoute( '/content/node/:nodeId', 'K1Controller', array( 'http-get' => 'view' ) ), 2 );
        $this->assertSame( array( 1, 2 ), $both->getVersions() );
        $this->assertSame( array( 2 ), $two->getVersions() );
        $this->assertSame( array( 3 ), ( new ezpRestVersionedRoute( $inner, '3' ) )->getVersions() );
        $this->assertSame( array( 1, 2 ), ( new ezpRestVersionedRoute( $inner, array( '1', 2, 1 ) ) )->getVersions() );
        foreach ( array( 1 => array( 'K1Controller::view', '404' ), 2 => array( 'K1Controller::view', 'K1Controller::view' ),
                         3 => array( '404', '404' ) ) as $version => $expected )
        {
            $this->version( $version );
            $this->assertSame( $expected[0], self::pick( array( $both ), 'GET', '/content/node/5' ), "v$version, route for v1 and v2" );
            $this->assertSame( $expected[1], self::pick( array( $two ), 'GET', '/content/node/5' ), "v$version, route for v2" );
        }
    }

    /** RM-05 */
    public function testGeneratedUrlKeepsTheCurrentVersion()
    {
        $route = new ezpRestVersionedRoute( new ezpMvcRailsRoute( '/content/node/:nodeId', 'K1Controller', array( 'http-get' => 'view' ) ), array( 1, 2 ) );
        $route->prefix( '/api' );
        $this->version( 1 );
        $this->assertSame( '/api/ezp/v1/content/node/7', $route->generateUrl( array( 'nodeId' => 7 ) ) );
        $this->version( 2 );
        $this->assertSame( '/api/ezp/v2/content/node/7', $route->generateUrl( array( 'nodeId' => 7 ) ) );
        $this->version( 5 );
        $this->assertSame( '/api/ezp/v1/content/node/7', $route->generateUrl( array( 'nodeId' => 7 ) ), 'not one of its versions: the first' );
    }

    /** RM-06 */
    public function testRouteFromTheOldCacheStillAnswers()
    {
        $route = new ezpRestVersionedRoute( new ezpMvcRailsRoute( '/content/node/:nodeId', 'K1Controller', array( 'http-get' => 'view' ) ), 2 );
        ( new ReflectionProperty( 'ezpRestVersionedRoute', 'versions' ) )->setValue( $route, null );
        $this->assertSame( array( 2 ), $route->getVersions() );
        $this->version( 2 );
        $this->assertSame( 'K1Controller::view', self::pick( array( $route ), 'GET', '/content/node/5' ) );
    }

    /** RM-07 */
    public function testAuthenticationAndErrorRoutesAnswerEveryMethod()
    {
        $map = ezpMvcRailsRoute::anyMethod( 'show' );
        foreach ( array( 'get', 'head', 'post', 'put', 'patch', 'delete', 'options' ) as $method )
            $this->assertSame( 'show', $map['http-' . $method ] );

        $provider = new ezpRestAuthProvider();
        $routes = $provider->getRoutes();
        foreach ( array( 'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS' ) as $method )
        {
            $this->assertSame( 'ezpRestAuthController::oauthRequired', self::pick( $routes, $method, '/oauth/login' ), $method );
            $this->assertSame( 'ezpRestAuthController::basicAuth', self::pick( $routes, $method, '/http-basic-auth' ), $method );
        }
        $this->assertSame( 'ezpRestOauthTokenController::handleRequest', self::pick( $routes, 'POST', '/oauth/token' ) );
        $this->assertSame( '405 OPTIONS,POST', self::pick( $routes, 'GET', '/oauth/token' ), 'the token endpoint stays POST only' );
    }

    /** RM-08 */
    public function testEzpProviderRoutes()
    {
        if ( !class_exists( 'ezp7xRestApiProvider' ) )
            $this->markTestSkipped( 'the ezprestapi extension is not installed' );
        $provider = new ezp7xRestApiProvider();
        $this->assertTrue( ezp7xRestApiProvider::kernelTakesVersionLists() );
        $routes = $provider->getRoutes();
        $c = 'ezp7xRestContentController::';
        $table = array(
            // version, method, path, expected
            array( 1, 'GET', '/content/node/863/list/offset/0/limit/20', $c . 'list' ),
            array( 2, 'GET', '/content/node/863/list/offset/0/limit/20', $c . 'list' ),
            array( 1, 'GET', '/content/node/2', $c . 'viewContent' ),
            array( 2, 'GET', '/content/node/2', $c . 'viewContent' ),
            array( 1, 'GET', '/content/node/2/fields', $c . 'viewFields' ),
            array( 1, 'GET', '/content/node/2/field/title', $c . 'viewField' ),
            array( 1, 'GET', '/content/node/2/childrenCount', $c . 'countChildren' ),
            array( 1, 'GET', '/content/object/1', $c . 'viewContent' ),
            array( 2, 'GET', '/content/object/1/fields', $c . 'viewFields' ),
            array( 2, 'GET', '/content/node/2/listAtom', 'ezpRestAtomController::collection' ),
            array( 2, 'POST', '/content/node/create', $c . 'CreateContentNode' ),
            array( 2, 'POST', '/content/node/delete/5', $c . 'DeleteContentNode' ),
            array( 2, 'DELETE', '/content/node/delete/5', $c . 'DeleteContentNode' ),
            array( 2, 'POST', '/content/node/5', $c . 'UpdateContentNode' ),
            // v1 is read only
            array( 1, 'POST', '/content/node/create', '405 GET,OPTIONS' ),
            array( 1, 'POST', '/content/node/5', '405 GET,OPTIONS' ),
            array( 1, 'DELETE', '/content/node/delete/5', '404' ),
            array( 2, 'PUT', '/content/node/5', '405 GET,OPTIONS,POST' ),
            array( 2, 'GET', '/content/node/delete/5', '405 DELETE,OPTIONS,POST' ),
            array( 3, 'GET', '/content/node/2', '404' ),
        );
        foreach ( $table as $row )
        {
            $this->version( $row[0] );
            $this->assertSame( $row[3], self::pick( $routes, $row[1], $row[2] ), "v{$row[0]} {$row[1]} {$row[2]}" );
        }
    }
}
