{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri='design:notification/parts/style.tpl'}
<div class="nf" id="exp-notify-added">
    <div class="nf-head"><div><h1>{'Add to my notifications'|i18n( 'design/admin/notification/addingresult' )}</h1></div></div>
{let node=fetch( content, node, hash( node_id, $node_id) )}
    <div class="nf-notice nf-notice-{if $already_exists}info{else}success{/if}" role="status"><p>
{if $already_exists}
        {'Notification for node <%node_name> already exists.'|i18n( 'design/admin/notification/addingresult',, hash( '%node_name', $node.name ) )|wash}
{else}
        {'Notification for node <%node_name> was added successfully.'|i18n( 'design/admin/notification/addingresult',, hash( '%node_name', $node.name ) )|wash}
{/if}
    </p></div>
{/let}
    <div class="nf-actions">
        <a class="nf-btn primary" href={first_set( $redirect_uri, $redirect_url, '/' )|ezurl}>{'OK'|i18n( 'design/admin/notification/addingresult' )}</a>
        <a class="nf-btn" href={'notification/settings'|ezurl}>{'My notification settings'|i18n( 'design/admin/notification/addingresult' )}</a>
    </div>
</div>
