{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let page_limit=30
     can_edit=false()}
{*     list_count=fetch('content','draft_count')} *}
<form action={concat("content/bookmark/")|ezurl} method="post" >

<div class="maincontentheader">
<h1>{"My bookmarks"|i18n("design/standard/content/view")}</h1>
</div>

{let bookmark_list=fetch('content','bookmarks',array())}

{section show=$bookmark_list}

<p>
    {"These are the objects you have bookmarked. Click on an object to view it or if you have permission you can edit the object by clicking the edit button.
      If you want to add more objects to this list click the %emphasize_startAdd bookmarks%emphasize_stop button.

      Removing objects will only remove them from this list."
      |i18n("design/standard/content/view",,
            hash( '%emphasize_start', '<i>',
                  '%emphasize_stop', '</i>' ) )
      |nl2br}
</p>

{section loop=$bookmark_list}
  {if $:item.node.object.can_edit}
    {set can_edit=true()}
  {/if}
{/section}

{if is_set( $bookmark_notice )}
<div class="{if eq( $bookmark_notice.level, 'error' )}warning{else}feedback{/if}"><h2>{$bookmark_notice.text|wash}</h2></div>
{/if}
<div class="exp-bm-page" data-exp-bm-page="1">
{include uri='design:content/bookmark_tree.tpl' mode='page'}
</div>
<div class="buttonblock"><input type="image" name="RemoveButton" value="{'Remove'|i18n('design/standard/content/view')}" src={"trash.png"|ezimage} alt="{'Remove'|i18n('design/standard/content/view')}" /></div>
{*{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/content/draft'
         item_count=$list_count
         view_parameters=$view_parameters
         item_limit=$page_limit}
*}
{section-else}

<div class="feedback">
    <h2>{"You have no bookmarks"|i18n("design/standard/content/view")}</h2>
</div>

{/section}

<div class="buttonblock">
    <input class="defaultbutton" type="submit" name="AddButton" value="{'Add bookmarks'|i18n('design/standard/content/view')}" />
</div>


</form>

{include uri='design:content/bookmark_folder_forms.tpl' folders=fetch( 'content', 'bookmark_folders', hash() )}

{/let}

{/let}

