{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{set-block scope=root variable=subject}{'[%sitename] Digest for %date'
                                        |i18n("design/standard/notification",,
                                              hash('%date',currentdate()|l10n(datetime),
                                                   '%sitename',ezini("SiteSettings","SiteURL")))}{/set-block}
{"This digest email is to inform you on new items at %sitename."
 |i18n('design/standard/notification',,
       hash('%sitename',ezini("SiteSettings","SiteURL")))}

{* foreach and literal includes: inside a named section $date and $address were looked up in the section's namespace,
   and an include whose uri is computed does not get the variables passed to it, so every digest came out empty *}
{foreach fetch( 'notification', 'digest_handlers', hash( 'date', $date.timestamp, 'address', $address ) ) as $digest_handler}
{if $digest_handler.id_string|eq( 'ezsubtree' )}
{include handler=$digest_handler date=$date address=$address uri='design:notification/handler/ezsubtree/view/digest_plain.tpl'}
{elseif $digest_handler.id_string|eq( 'ezcollaboration' )}
{include handler=$digest_handler date=$date address=$address uri='design:notification/handler/ezcollaboration/view/digest_plain.tpl'}
{else}
{include handler=$digest_handler date=$date address=$address uri=concat( 'design:notification/handler/', $digest_handler.id_string, '/view/digest_plain.tpl' )}
{/if}
{/foreach}

{"If you do not want to continue receiving these notifications,
change your settings at:"|i18n('design/standard/notification')}
http://{ezini("SiteSettings","SiteURL")}{concat("notification/settings/")|ezurl(no)}

-- 
{"%sitename notification system"
 |i18n('design/standard/notification',,
       hash('%sitename',ezini("SiteSettings","SiteURL")))}
