{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"If you don't have access to a database, you should obtain access now. Exponential is capable of running multiple sites, each site needs its own database. This means that you need to create several databases if you plan to run multiple sites. Please refer to the database system user manual if you're unsure about how to create a database."|i18n("design/standard/setup/init")}
<p></p>
{"PostgreSQL: the username and password are tested against the database named here, which has to exist already; its owner can install Exponential into it. With no name, the Site details page lists the databases this user may connect to."|i18n("design/standard/setup/init")}
<p></p>
{"If you are using MySQL and do not know what to enter in the socket field, leave it blank"|i18n("design/standard/setup/init")}