{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{"Exponential supports SQLite, MySQL, PostgreSQL and MongoDB."|i18n("design/standard/setup/init")}
<p></p>
{"SQLite is the recommended choice: it needs no database server and keeps the whole database in one file inside the installation. It requires the PHP sqlite3 extension."|i18n("design/standard/setup/init")}
<p></p>
{"PostgreSQL or MySQL >= 4.1 are required for unicode support in Exponential."|i18n("design/standard/setup/init")|wash}
<p></p>
{"More information about Exponential and unicode support can be found %1."|i18n("design/standard/setup/init",,array(concat( '<a href="https://exponential.earth" target="_blank">', "here"|i18n("design/standard/setup/init", 'link to unicode info'), '</a>' ) ) )}
