{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}

<div align="center">
  <h1>{"Choose database system"|i18n("design/standard/setup/init")}</h1>
</div>

{if gt( $database_list|count, 0 )}
<p>
 {"Support for the following database systems was detected on your system:"|i18n("design/standard/setup/init")}
 {foreach $database_list as $index => $database}{if gt( $index, 0 )}, {/if}{$database.name|wash}{/foreach}.
 {"Please choose the database system you would like to use."|i18n("design/standard/setup/init")}
</p>
{/if}

{if $preferred_database_missing}
<div class="warning">
<p>
 {"%1 is the recommended database system for Exponential, but it cannot be used here: the PHP %2 extension is not loaded. %3 has been selected instead. To use %1, enable the %2 extension in PHP and start the setup wizard again."|i18n( "design/standard/setup/init",, array( $preferred_database.name|wash, $preferred_database.type|wash, cond( is_array( $database_info ), $database_info.name, '-' )|wash ) )}
</p>
</div>
{else}
<p>
 {"%1 is recommended: it needs no database server, and Exponential keeps the whole database in a single file inside the installation. The other database systems listed below remain available for sites that use a database server."|i18n( "design/standard/setup/init",, array( $preferred_database.name|wash ) )}
</p>
{/if}

<form method="post" action="{$script}">
<div class="input_highlight">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
  <th class="label" colspan="2">{"Database:"|i18n("design/standard/setup/init")}</th>
</tr>
{foreach $database_list as $database}
<tr>
  <td class="normal" rowspan="1" valign="top">
  <input type="radio" id="eZSetupDatabase{$database.type}" name="eZSetupDatabaseType" value="{$database.type}" {if and( is_array( $database_info ), eq( $database.type, $database_info.type ) )}checked="checked" {/if}/>
  </td>
  <td class="normal"><label class="radio" for="eZSetupDatabase{$database.type}">{$database.name|wash}{if $database.recommended} ({"recommended"|i18n("design/standard/setup/init")}){/if}</label></td>
</tr>
{/foreach}
</table>
</div>

  {include uri='design:setup/init/navigation.tpl'}
  {include uri='design:setup/persistence.tpl'}
</form>
