{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}

<div align="center">
  <h1>{"Package language options"|i18n("design/standard/setup/init")}</h1>
</div>
<p>

<form method="post" action="{$script}">

<fieldset>
  <legend>{"Language mapping"|i18n("design/standard/setup/init")}</legend>
<p>
{"The languages you have chose for site do not match languages in chosen packages. To resolve conflict please select language mapping:"|i18n("design/standard/setup/init")}
</p>

  <table class="list" cellspacing="0">
  <tr>
    <th>{'Language'|i18n( 'design/standard/setup/init' )}</th>
    <th>{'Action'|i18n( 'design/standard/setup/init' )}</th>
  </tr>
  {foreach $package_language_list as $package_language}
    <tr>
        <td>{$package_language.name}</td>
        <td>
            <select name={concat("eZSetupPackageLanguageMap[", $package_language.locale, "]")}>
                {foreach $site_language_list as $site_language_key => $site_language}
                    <option value="{$site_language.locale}">{concat('Map to '|i18n( 'design/standard/setup/init' ),$site_language.name)}</option>
                {/foreach}
                <option value="{$package_language.locale}" selected="selected">{'Create language'|i18n( 'design/standard/setup/init' )}</option>
                <option value="skip">{'Skip content in this language'|i18n( 'design/standard/setup/init' )}</option>
            </select>
        </td>
    </tr>
  {/foreach}
  </table>

<p>
<em>{"Notice: Creating the language keeps the package content in the language it was written in, next to the languages you chose. Mapping it relabels that content as another language without translating it."|i18n("design/standard/setup/init")}</em>
</p>

</fieldset>

{include uri="design:setup/persistence.tpl"}

<div class="buttonblock">
  {include uri='design:setup/init/navigation.tpl'}
</div>


</form>
</p>

