{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}

<form method="post" action="{$script}">

  <div align="center">
    <h1>{"Site access configuration"|i18n("design/standard/setup/init")}</h1>
  </div>

  <p>
    {"Please choose the access method you want to use for your site. The access method determines how the site will be accessed from within a web browser. If unsure: choose URL."|i18n("design/standard/setup/init")|break}
  </p>

  <p>
    {"Every installation gets three siteaccesses: the site itself, the admin siteaccess (the full administration interface) and the editor siteaccess (the administration interface for content editing only, without setup, design and developer tools). The next step lets you name the path, port or host name of each."|i18n("design/standard/setup/init")}
  </p>
  <p>
    {"With hostname access the convention is %site for the site, %admin for the administration and %editor for content editing."|i18n("design/standard/setup/init",, hash( '%site', '<nobr><b>yourdomain.com</b></nobr>', '%admin', '<nobr><b>admin.yourdomain.com</b></nobr>', '%editor', '<nobr><b>edit.yourdomain.com</b></nobr>' ))}
  </p>

  <p>
  <fieldset>
  <legend>{'Access method'|i18n( 'design/standard/setup/init' )}:</legend>
    <table border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td class="normal">
          <input type="radio" id="eZSetup_site_access_url" name="eZSetup_site_access" value="url" {if $site_type.access_type|eq( 'url' )}checked="checked"{/if} /><label class="radio" for="eZSetup_site_access_url">{"URL (recommended)"|i18n("design/standard/setup/init")}</label>
        </td>
      </tr>
      <tr>
        <td class="normal">
{*          <input type="radio" name="eZSetup_site_access" value="port">{"Port. Note: Requires web server configuration "|i18n("design/standard/setup/init")}</input>*}
          <input type="radio" id="eZSetup_site_access_port" name="eZSetup_site_access" value="port" {if $site_type.access_type|eq( 'port' )}checked="checked"{/if} /><label class="radio" for="eZSetup_site_access_port">{"Port"|i18n("design/standard/setup/init")}</label>
        </td>
      </tr>
      <tr>
        <td class="normal">
{*          <input type="radio" name="eZSetup_site_access" value="hostname">{"Hostname. Note: Requires DNS setup."|i18n("design/standard/setup/init")}</input>*}
          <input type="radio" id="eZSetup_site_access_host" name="eZSetup_site_access" value="hostname" {if $site_type.access_type|eq( 'hostname' )}checked="checked"{/if} /><label class="radio" for="eZSetup_site_access_host">{"Hostname"|i18n("design/standard/setup/init")}</label>
        </td>
      </tr>
    </table>
  </fieldset>
  </p>

  {include uri='design:setup/init/navigation.tpl'}
  {include uri="design:setup/persistence.tpl"}

</form>
