{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* Footer options:
   Example, 
   hash( text, "Page: #page/#total #level1 - #indexLevel1",
               // #page is replaces by current page number
               // #total is replaced by total number of pagee
	       // #level<X> display header name of level X
	       // #indexLevel<X> display header index number of level X
	 page, "odd|even|all",
	 pageOffset, 0,
	 // default all
	 align, "left|right|center|",
	 // default = left
	 size, 13,
	 font, Courier,

	 margin, hash( top, 5,
	               bottom, 5,
		       left, 5,
		       right, 5,
		       height, 30 ),
         // frame margins from page sides.

	 line, hash( margin, 30,
                     thicknes, "1.5",
		     leftMargin, 20,
		     rightMargin, 30,
		     page, "odd|even|all",
		     pageOffset, 0 ) )  *}

{* The left hand footer line belongs to the export, which sets show_footer and
   footer_text from its own edit page. Neither is set when a pdf is produced
   some other way, so the wording that was hard coded here is still the
   default. *}
{default show_footer=1
         footer_text=''}
{if $show_footer|eq(1)}
  {if $footer_text|ne('')}
    {pdf(footer, hash( text, $footer_text|wash(pdf),
                       size, 10,
                       align, "left" ) ) }
  {else}
    {pdf(footer, hash( text, "Exponential PDF export"|i18n( "design/standard/content/pdf" )|wash(pdf),
                       size, 10,
                       align, "left" ) ) }
  {/if}
{/if}
{/default}
{pdf(footer, hash( text, "#page of #total"|i18n( "design/standard/content/pdf" )|wash(pdf),
                   align, "right",
		   size, 10 ) ) }
{pdf(footer, hash( line, hash( margin, 80,
		               thicknes, 1,
			       size, "full" ) ) ) }