{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="package" class="create">
    <div id="sid-{$current_step.id|wash}" class="pc-{$creator.id|wash}">

    <form method="post" action={'package/create'|ezurl}>

    {include uri="design:package/create/error.tpl"}

    {include uri="design:package/header.tpl"}

    <p>{'Provide some basic information for your package.'|i18n('design/standard/package')}</p>

    <table>
    <tr>

    <td valign="top">
        <div class="name">
            <label>{'Package name'|i18n('design/standard/package')}</label>
            <input class="textline" type="text" name="PackageName" value="{$persistent_data.name|wash}" />
        </div>

        <div class="summary">
            <label>{'Summary'|i18n('design/standard/package')}</label>
            <input class="textline" type="text" name="PackageSummary" value="{$persistent_data.summary|wash}" />
        </div>

        <div class="description">
            <label>{'Description'|i18n('design/standard/package')}</label>
            <textarea class="description" name="PackageDescription">{$persistent_data.description|wash}</textarea>
        </div>

        <div class="version">
            <label>{'Version'|i18n('design/standard/package')}</label>
            <input class="shorttextline" type="text" name="PackageVersion" value="{$persistent_data.version|wash}" />
        </div>

        <div class="licence">
            <label for="PackageLicence">{'License'|i18n('design/standard/package')}</label>
            {* A strict choice from package.ini [LicenseSettings]; the server refuses any other value *}
            {if $licence_groups|count|gt( 0 )}
            <select id="PackageLicence" name="PackageLicence" style="max-width: 100%;">
            {foreach $licence_groups as $group}
                <optgroup label="{$group.name|wash}">
                {foreach $group.licenses as $license}
                    <option value="{$license.identifier|wash}"{if $license.identifier|eq( $licence_selected.identifier )} selected="selected"{/if}>{$license.name|wash} ({$license.identifier|wash})</option>
                {/foreach}
                </optgroup>
            {/foreach}
            </select>
            {if $licence_selected.url}
            <p>{'License text:'|i18n('design/standard/package')} <a href="{$licence_selected.url|wash}" target="_blank" rel="noopener noreferrer">{$licence_selected.name|wash}</a></p>
            {/if}
            {else}
            <p>{'No licenses are configured for packages. Add them to package.ini [LicenseSettings] LicenseList.'|i18n('design/standard/package')}</p>
            {/if}
        </div>
    </td>

    <td valign="top">
        <div class="name">
            <label>{'Package host'|i18n('design/standard/package')}</label>
            <input class="textline" type="text" name="PackageHost" value="{$persistent_data.host|wash}" />
        </div>

        <div class="summary">
            <label>{'Packager'|i18n('design/standard/package')}</label>
            <input class="textline" type="text" name="PackagePackager" value="{$persistent_data.packager|wash}" />
        </div>
    </td>

    </tr>
    </table>

    {include uri="design:package/navigator.tpl"}

    </form>

    </div>
</div>
