<?php
/**
 * The audit keys (doc/bc/6.0/audit.md, "Keys (Z7)", "Key handling"): the installation id (a UUID, part of every
 * channel's genesis hash), the signing keys (HMAC-SHA-256 of checkpoints and, from stage 5, archive manifests)
 * and the pseudonym key (the "hash" privacy option).
 *
 * Read from audit.ini [AuditKeySettings] as eZINI merges it (a site may provide its own keys in any settings
 * file), else from the key file settings/override/audit.ini.append.php read directly (so a key generated by
 * another process a moment ago is found even though the INI cache still has the old file), else generated on
 * first use with random_bytes() and written into that file through expIniEditor (atomic, mode 0640, owned like
 * settings/override also when the process runs as root). Generation runs under a lock in the log directory, so
 * two processes never make two different keys. settings/override is never committed.
 *
 * Variable names: InstallationID, ActiveSigningKey, SigningKey[<key id>], PseudonymKey; expIniEditor::isSecret()
 * masks SigningKey and PseudonymKey (they end in "Key" after a lower-case letter), so exp:ini, the debug bar and
 * the settings views never show them.
 *
 * @copyright Copyright (C) 1998 - 2026 7x & Exponential Foundation. All rights reserved.
 * @license GNU General Public License v2.0 (or any later version)
 * @package kernel
 */

class expAuditKeys
{
    const BLOCK = 'AuditKeySettings';

    /** @var array|null The keys this process knows: installation, active, signing (id => raw bytes), pseudonym (raw) */
    protected static $known = null;

    /** @var string|null The key directory the known keys came from */
    protected static $knownDir = null;

    /** @var bool True while this process writes the key file (the write is not itself audited as a setting) */
    protected static $generating = false;

    /** @var array Keys generated by this process and not yet recorded: key_id, fingerprint, file */
    protected static $created = array();

    /** @var array */
    protected $config;

    /**
     * @param array $config expAuditConfig::get()
     */
    public function __construct( array $config )
    {
        $this->config = $config;
    }

    /** @return bool This process is writing the key file right now */
    public static function isGenerating()
    {
        return self::$generating;
    }

    /**
     * The keys generated since the last call (for system.audit.key.create), emptied.
     *
     * @return array[]
     */
    public static function takeCreated()
    {
        $c = self::$created;
        self::$created = array();
        return $c;
    }

    /** Forgets the keys of this process (tests). */
    public static function reset()
    {
        self::$known = null;
        self::$knownDir = null;
    }

    /** @return string The key file: <keyDir>/audit.ini.append.php */
    public function keyFile()
    {
        return $this->config['keyDir'] . '/audit.ini.append.php';
    }

    /**
     * The keys, generated when missing (and GenerateKeys=enabled).
     *
     * @param bool $generate
     * @return array installation, active, signing (id => raw), pseudonym (raw); empty strings when there are none
     */
    public function keys( $generate = true )
    {
        if ( self::$known !== null && self::$knownDir === $this->config['keyDir'] && self::complete( self::$known ) )
            return self::$known;
        $keys = self::decodeKeys( $this->config['keys'] );
        if ( !self::complete( $keys ) )
        {
            $fromFile = $this->readFile();
            $keys = self::merge( $keys, $fromFile );
        }
        if ( !self::complete( $keys ) && $generate && $this->config['generateKeys'] )
            $keys = $this->generate( $keys );
        self::$known = $keys;
        self::$knownDir = $this->config['keyDir'];
        return $keys;
    }

    /** @return string The installation id ('' when there is none) */
    public function installationId()
    {
        $k = $this->keys();
        return $k['installation'];
    }

    /** @return string|null The raw pseudonym key */
    public function pseudonymKey()
    {
        $k = $this->keys();
        return $k['pseudonym'] !== '' ? $k['pseudonym'] : null;
    }

    /** @return string The active signing key id ('' when there is none) */
    public function activeKeyId()
    {
        $k = $this->keys();
        return $k['active'];
    }

    /**
     * @param string|null $id null = the active key
     * @return string|null raw key bytes
     */
    public function signingKey( $id = null )
    {
        $k = $this->keys();
        $id = $id === null ? $k['active'] : $id;
        return isset( $k['signing'][$id] ) ? $k['signing'][$id] : null;
    }

    /**
     * The fingerprint shown for a key: the first 16 hex digits of SHA-256(key) in groups of four, upper case.
     *
     * @param string $raw
     * @return string
     */
    public static function fingerprint( $raw )
    {
        return strtoupper( implode( ' ', str_split( substr( hash( 'sha256', $raw ), 0, 16 ), 4 ) ) );
    }

    /**
     * "hmac-sha256:" + hex HMAC-SHA-256 of the canonical JSON of $data with a signing key.
     *
     * @param mixed $data
     * @param string|null $keyId null = the active key
     * @return string|null null without a key
     */
    public function sign( $data, $keyId = null )
    {
        $key = $this->signingKey( $keyId );
        if ( $key === null )
            return null;
        return 'hmac-sha256:' . hash_hmac( 'sha256', expAuditJson::encode( $data ), $key );
    }

    /**
     * @param array $keys
     * @return bool installation, active signing key and pseudonym key are all there
     */
    protected static function complete( array $keys )
    {
        return $keys['installation'] !== '' && $keys['pseudonym'] !== '' && $keys['active'] !== ''
               && isset( $keys['signing'][$keys['active']] );
    }

    /**
     * The settings form (base64 strings) as raw keys.
     *
     * @param array $settings installation, active, signing (id => base64), pseudonym (base64)
     * @return array
     */
    protected static function decodeKeys( array $settings )
    {
        $signing = array();
        foreach ( (array)( isset( $settings['signing'] ) ? $settings['signing'] : array() ) as $id => $b64 )
        {
            $raw = base64_decode( (string)$b64, true );
            if ( $raw !== false && strlen( $raw ) >= 16 )
                $signing[(string)$id] = $raw;
        }
        $pseudonym = isset( $settings['pseudonym'] ) ? base64_decode( (string)$settings['pseudonym'], true ) : false;
        return array(
            'installation' => isset( $settings['installation'] ) ? (string)$settings['installation'] : '',
            'active' => isset( $settings['active'] ) ? (string)$settings['active'] : '',
            'signing' => $signing,
            'pseudonym' => $pseudonym !== false && strlen( $pseudonym ) >= 16 ? $pseudonym : '',
        );
    }

    /** @return array $a completed with what $a lacks from $b */
    protected static function merge( array $a, array $b )
    {
        foreach ( array( 'installation', 'active', 'pseudonym' ) as $k )
            if ( $a[$k] === '' )
                $a[$k] = $b[$k];
        $a['signing'] = $a['signing'] + $b['signing'];
        return $a;
    }

    /**
     * The keys in the key file, read directly (not through the INI cache).
     *
     * @return array
     */
    protected function readFile()
    {
        $empty = self::decodeKeys( array() );
        $file = $this->keyFile();
        if ( !is_file( $file ) || !class_exists( 'expIniWriter' ) )
            return $empty;
        try
        {
            $values = expIniWriter::fromFile( $file )->values();
        }
        catch ( Throwable $e )
        {
            return $empty;
        }
        $b = isset( $values[self::BLOCK] ) ? $values[self::BLOCK] : array();
        return self::decodeKeys( array(
            'installation' => isset( $b['InstallationID'] ) ? $b['InstallationID'] : '',
            'active' => isset( $b['ActiveSigningKey'] ) ? $b['ActiveSigningKey'] : '',
            'signing' => isset( $b['SigningKey'] ) ? (array)$b['SigningKey'] : array(),
            'pseudonym' => isset( $b['PseudonymKey'] ) ? $b['PseudonymKey'] : '',
        ) );
    }

    /**
     * Generates what is missing, under a lock, and writes it into the key file.
     *
     * @param array $keys what is known already
     * @return array
     */
    protected function generate( array $keys )
    {
        $lock = null;
        $lockDir = $this->config['logDir'];
        if ( expAuditWriter::ensureDirectory( $lockDir ) )
        {
            $lockFile = $lockDir . '/.keys.lock';
            $created = !is_file( $lockFile );
            $lock = @fopen( $lockFile, 'c' );
            if ( $lock )
            {
                if ( $created )
                    expAuditWriter::ownLikeParent( $lockFile, 0640 );
                flock( $lock, LOCK_EX );
            }
        }
        try
        {
            // another process may have written them while this one waited
            $keys = self::merge( $keys, $this->readFile() );
            if ( self::complete( $keys ) )
                return $keys;

            $new = array();
            if ( $keys['installation'] === '' )
                $keys['installation'] = $new['InstallationID'] = self::uuid();
            if ( $keys['pseudonym'] === '' )
            {
                $keys['pseudonym'] = random_bytes( 32 );
                $new['PseudonymKey'] = base64_encode( $keys['pseudonym'] );
            }
            $created = array();
            if ( $keys['active'] === '' || !isset( $keys['signing'][$keys['active']] ) )
            {
                $raw = random_bytes( 32 );
                $id = self::keyId( count( $keys['signing'] ) + 1, $raw );
                $keys['signing'][$id] = $raw;
                $keys['active'] = $id;
                $new['ActiveSigningKey'] = $id;
                $new['SigningKey'] = array( $id => base64_encode( $raw ) );
                $created[] = $id;
            }
            if ( !$this->writeFile( $new ) && class_exists( 'eZDebug' ) )
                eZDebug::writeError( 'The audit keys could not be written to ' . $this->keyFile() . '; they are used for this process only', __METHOD__ );
            // recorded by expAudit once no channel is locked (system.audit.key.create)
            foreach ( $created as $id )
                self::$created[] = array( 'key_id' => $id, 'fingerprint' => self::fingerprint( $keys['signing'][$id] ),
                                          'file' => $this->relative( $this->keyFile() ) );
            return $keys;
        }
        finally
        {
            if ( $lock )
            {
                flock( $lock, LOCK_UN );
                fclose( $lock );
            }
        }
    }

    /**
     * Writes new values into the key file through expIniEditor (atomic, owner of settings/override kept).
     *
     * @param array $new variable => value (SigningKey: id => value)
     * @return bool
     */
    protected function writeFile( array $new )
    {
        if ( !$new )
            return true;
        if ( !class_exists( 'expIniEditor' ) || !class_exists( 'expIniScope' ) )
            return false;
        $dir = $this->config['keyDir'];
        $root = dirname( $dir ) . '/';
        $scope = new expIniScope( 'audit-keys', expIniScope::KIND_GLOBAL, basename( $dir ), $root, 'Audit keys' );
        self::$generating = true;
        try
        {
            $existed = is_file( $scope->path( 'audit.ini' ) );
            $editor = new expIniEditor( $scope, 'audit.ini' );
            foreach ( $new as $var => $value )
            {
                if ( is_array( $value ) )
                    foreach ( $value as $k => $v )
                        $editor->set( self::BLOCK, $var, $v, $k );
                else
                    $editor->set( self::BLOCK, $var, $value );
            }
            $editor->save( array( 'backup' => false ) );
            if ( !$existed )
                @chmod( $scope->path( 'audit.ini' ), 0640 );
            return true;
        }
        catch ( Throwable $e )
        {
            if ( class_exists( 'eZDebug' ) )
                eZDebug::writeError( 'Audit keys: ' . $e->getMessage(), __METHOD__ );
            return false;
        }
        finally
        {
            self::$generating = false;
        }
    }

    /** @return string k<n>-<YYYYMMDD>-<first 8 hex of SHA-256(key)> */
    public static function keyId( $n, $raw )
    {
        return 'k' . (int)$n . '-' . gmdate( 'Ymd' ) . '-' . substr( hash( 'sha256', $raw ), 0, 8 );
    }

    /** @return string A random (version 4) UUID */
    public static function uuid()
    {
        $b = random_bytes( 16 );
        $b[6] = chr( ( ord( $b[6] ) & 0x0f ) | 0x40 );
        $b[8] = chr( ( ord( $b[8] ) & 0x3f ) | 0x80 );
        return vsprintf( '%s%s-%s-%s-%s-%s%s%s', str_split( bin2hex( $b ), 4 ) );
    }

    /** @return string A path relative to the installation root when inside it */
    protected function relative( $path )
    {
        $root = expAuditConfig::root();
        return strncmp( $path, $root, strlen( $root ) ) === 0 ? substr( $path, strlen( $root ) ) : $path;
    }

    /**
     * Sets the keys of this process (tests: no file is read or written).
     *
     * @param array|null $keys installation, active, signing (id => raw), pseudonym (raw); null forgets them
     * @param string|null $keyDir the key directory they count for (null = any)
     */
    public static function setKnown( ?array $keys = null, $keyDir = null )
    {
        self::$known = $keys;
        self::$knownDir = $keyDir;
    }
}
