{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form action={concat( $module.functions.view.uri, '/', $role.id, $policy_uri_suffix, $assignment_uri_suffix )|ezurl} method="post" >
{* Enter in the name filter presses the first button of the form, which must not be Edit *}
{if or( $assignment_total|gt( $assignment_limit ), $assignment_filter )}<input type="submit" name="AssignmentFilterButton" value="{'Filter'|i18n( 'design/admin/role/view' )}" tabindex="-1" aria-hidden="true" style="position: absolute; left: -10000px; width: 1px; height: 1px; overflow: hidden;" />{/if}

<div class="maincontentheader">
    <h1>{"Role view"|i18n("design/standard/role")}</h1>
</div>

<div class="objectheader">
    <h2>{"Role"|i18n("design/standard/role")}</h2>
</div>
<div class="object">
    <label>{"Name"|i18n("design/standard/role")}</label><div class="labelbreak"/>
    <p class="box">{$role.name|wash}</p>
    <input class="button" type="submit" name="EditRoleButton" value="{'Edit'|i18n('design/standard/role')}" title="{'Edit current role'|i18n('design/standard/role')}" />
</div>

<h2>{"Role policies"|i18n("design/standard/role")}</h2>

<table class="list" width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
    <th>{"Module"|i18n("design/standard/role")}</th>
    <th>{"Function"|i18n("design/standard/role")}</th>
    <th>{"Limitation"|i18n("design/standard/role")}</th>
</tr>

{section name=Policy loop=$policies sequence=array(bglight,bgdark)}
<tr class="{$:sequence}">
    <td>
        {$Policy:item.module_name}
    </td>
    <td>
        {$Policy:item.function_name}
    </td>
    <td>
        {section show=$Policy:item.limitations}
          {section name=Limitation loop=$Policy:item.limitations}
              {$Policy:Limitation:item.label|wash}{if $Policy:Limitation:item.denies_without_handler} <em class="limitation-denies" title="{'No extension handler evaluates this limitation, so this policy gives no access'|i18n( 'design/admin/role/view' )|wash}">{'(no handler, denies)'|i18n( 'design/admin/role/view' )|wash}</em>{/if}(
              {section name=LimitationValues loop=$Policy:Limitation:item.values_as_array_with_names}
                  {$Policy:Limitation:LimitationValues:item.Name|wash}
                  {delimiter}, {/delimiter}
              {/section})
              {delimiter}, {/delimiter}
          {/section}
        {section-else}
	  *
        {/section}
    </td>
</tr>
{/section}
</table>

<h2>{"Users and groups assigned to this role"|i18n("design/standard/role")} ({$assignment_total})</h2>

{if or( $assignment_total|gt( $assignment_limit ), $assignment_filter )}
<p>
    <label for="role-assignment-filter">{'Name contains'|i18n( 'design/admin/role/view' )}:</label>
    <input type="search" id="role-assignment-filter" name="AssignmentFilter" value="{$assignment_filter|wash}" size="30" maxlength="100" />
    <input class="button" type="submit" name="AssignmentFilterButton" value="{'Filter'|i18n( 'design/admin/role/view' )}" />
    {if $assignment_filter}
        <input class="button" type="submit" name="AssignmentFilterClearButton" value="{'Show all'|i18n( 'design/admin/role/view' )}" />
        {'%count of %total match "%filter".'|i18n( 'design/admin/role/view',, hash( '%count', $assignment_count, '%total', $assignment_total, '%filter', $assignment_filter ) )|wash}
    {/if}
</p>
{/if}
{if $assignment_orphan_count}
<p>{'%count of these assignments belong to a user or user group that no longer exists. They are listed first and can be removed.'|i18n( 'design/admin/role/view',, hash( '%count', $assignment_orphan_count ) )|wash}</p>
{/if}

<table class="list" width="100%" cellspacing="0" cellpadding="0" border="0">
<tr>
    <th width="79%">{"User"|i18n("design/standard/role")}</th>
    <th width="20%">{"Limitation"|i18n("design/standard/role")}</th>
    <th width="1">&nbsp;</th>
</tr>
{section name=User loop=$user_array sequence=array(bglight,bgdark)}
<tr>
    <td class="{$User:sequence}">
        {if $User:item.user_object}
            {$User:item.user_object.class_identifier|class_icon( 'small', $User:item.user_object.class_name )}{$User:item.user_name|wash}
        {else}
            <i>{'User or user group no longer exists (object %object_id)'|i18n( 'design/admin/role/view',, hash( '%object_id', $User:item.user_id ) )}</i>
        {/if}
    </td>
    <td class="{$User:sequence}">
        {if $User:item.limit_ident}
          {if $User:item.limit_node}
            {$User:item.limit_ident|wash}( {$User:item.limit_node.name|wash} )
          {elseif $User:item.limit_section}
            {$User:item.limit_ident|wash}( {$User:item.limit_section.name|wash} )
          {else}
            {$User:item.limit_ident|wash}( {$User:item.limit_value|wash} )
          {/if}
        {/if}
    </td>
    <td class="{$User:sequence}">
        <input type="checkbox" value="{$User:item.user_role_id}" name="IDArray[]" />
    </td>
</tr>
{/section}
{if $assignment_count|gt( $assignment_limit )}
<tr>
    <td colspan="3">
    {* Previous and next on (assignment_offset), keeping the place of the policies and the
       name filter: the navigator of this design pages on (offset) only *}
    {if $assignment_offset|gt( 0 )}
        <a href={concat( $policy_page_uri, $policy_uri_suffix, '/(assignment_offset)/', max( 0, sub( $assignment_offset, $assignment_limit ) ), $assignment_filter_uri_suffix )|ezurl}>&laquo;&nbsp;{'Previous'|i18n( 'design/standard/navigator' )}</a>
    {/if}
    {if sum( $assignment_offset, $assignment_limit )|lt( $assignment_count )}
        <a href={concat( $policy_page_uri, $policy_uri_suffix, '/(assignment_offset)/', sum( $assignment_offset, $assignment_limit ), $assignment_filter_uri_suffix )|ezurl}>{'Next'|i18n( 'design/standard/navigator' )}&nbsp;&raquo;</a>
    {/if}
    </td>
</tr>
{/if}
<tr>
    <td>
        <input class="button" type="submit" name="AssignRoleButton" value="{'Assign'|i18n('design/standard/role')}" title="{'Assign role to user or group'|i18n('design/standard/role')}" />
        <input class="button" type="submit" name="AssignRoleLimitedButton" value="{'Assign limited'|i18n('design/standard/role')}" title="{'Assign role to user or group'|i18n('design/standard/role')}" />on
	<select name="AssignRoleType">
	    <option value="subtree">{"Subtree"|i18n( 'design/standard/role' )}</option>
	    <option value="section">{"Section"|i18n( 'design/standard/role' )}</option>
	</select>
    </td>
    <td>
      &nbsp;
    </td>
    <td align="right" width="1">
        <input type="image" name="RemoveRoleAssignmentButton" value="{'Remove'|i18n('design/standard/role')}" title="{'Remove selected assignments'|i18n('design/standard/role')}" src={"trash.png"|ezimage} />
    </td>
</tr>
</table>

</form>