{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{if is_unset( $load_javascript_list )}
 {def $load_javascript_list = true()}
{/if}

{include uri='design:page_head_exp.tpl'}

{if $load_javascript_list}
 {ezscript_load( ezini( 'JavaScriptSettings', 'BackendJavaScriptList', 'design.ini' )|prepend( 'ezjsc::jquery', 'ezjsc::jqueryio' ) )}
{else}
 {ezscript_load( array( 'ezjsc::jquery', 'ezjsc::jqueryio' ) )}
{/if}
{* admin4: keeps the page clear of the fixed header, whose menu wraps onto more lines on narrower windows. Loaded
   through ezscript_load so its URL carries the file's time: the plain file was served with a one-year cache
   lifetime and browsers kept an old copy after an update. *}
{ezscript_load( array( 'admin4.js' ) )}
