{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* A stored URL with a script or data scheme (javascript:, vbscript:, data:) is
   shown as text, never as a link: display_info.view.url_is_linkable is set by
   eZURLType, which recognises the scheme also when it is disguised. *}
{if $attribute.display_info.view.url_is_linkable}
{if $attribute.data_text}
<a href="{$attribute.content|wash( xhtml )}">{$attribute.data_text|wash( xhtml )}</a>
{else}
<a href="{$attribute.content|wash( xhtml )}">{$attribute.content|wash( xhtml )}</a>
{/if}
{else}
{if $attribute.data_text}{$attribute.data_text|wash( xhtml )}{else}{$attribute.content|wash( xhtml )}{/if}
{/if}