{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{'Content extension wizard'|i18n('design/standard/setup')}</h1>
<p>{'A content class written as a script rather than built by clicking, plus custom tags for rich text and a translation.'|i18n('design/standard/setup')}</p>

{foreach $wizard_problems as $ce_problem}
<p class="warning">{$ce_problem|wash}</p>
{/foreach}

<form method="post" action={'setup/contentextension'|ezurl}>
<input type="hidden" name="Submitted" value="1" />

<h2>{'What this extension carries'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_topics as $ce_topic}
    <li><label><input type="checkbox" name="Parts[]" value="{$ce_topic.key|wash}"{if $ce_topic.chosen} checked="checked"{/if} />
        {$ce_topic.label|wash} &ndash; {$ce_topic.summary|wash}</label></li>
{/foreach}
</ul>

<p><label>{'Extension name'|i18n('design/standard/setup')}: <input type="text" name="name" value="{$wizard_settings.name|wash}" /></label></p>
<p><label>{'Class identifier'|i18n('design/standard/setup')}: <input type="text" name="class" value="{$wizard_settings.class|wash}" /></label></p>
<p><label>{'Attributes'|i18n('design/standard/setup')}:<br /><textarea name="attributes" rows="5" cols="60">{$wizard_raw.attributes|wash}</textarea></label></p>
<p><label>{'Custom tags'|i18n('design/standard/setup')}:<br /><textarea name="tags" rows="3" cols="60">{$wizard_raw.tags|wash}</textarea></label></p>
<p><label>{'Locale'|i18n('design/standard/setup')}: <input type="text" name="locale" value="{$wizard_settings.locale|wash}" /></label></p>
<p><label>{'Strings'|i18n('design/standard/setup')}:<br /><textarea name="strings" rows="3" cols="60">{$wizard_raw.strings|wash}</textarea></label></p>

{if $wizard_attributes|count|gt( 0 )}
<h2>{'As the script will make them'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_attributes as $ce_attribute}
    <li><code>{$ce_attribute.identifier|wash}</code> &ndash; <code>{$ce_attribute.type|wash}</code>{if $ce_attribute.known|not} ({'no such datatype here'|i18n('design/standard/setup')}){/if}</li>
{/foreach}
</ul>
{/if}

{if $wizard_file_count|gt( 0 )}
<h2>{'Every file, before it is written'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_files as $ce_file}
    <li><code>{$ce_file.path|wash}</code> &ndash; {$ce_file.lines} {'lines'|i18n('design/standard/setup')}</li>
{/foreach}
</ul>
{/if}

<p>
    {if $wizard_ready}<input type="submit" name="CreateButton" value="{'Create in extension/'|i18n('design/standard/setup')}" />{/if}
    <input type="submit" name="PreviewButton" value="{'Refresh preview'|i18n('design/standard/setup')}" />
</p>
</form>
