{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{'Datatype wizard'|i18n('design/standard/setup')}</h1>
<p>
    {'A datatype is a kind of value a content class attribute can hold, with its own editing field, validation, storage and display. Say what it has to do and only the methods that answer to that are written.'|i18n('design/standard/setup')}
</p>

{foreach $wizard_problems as $dw_problem}
<p class="warning">{$dw_problem|wash}</p>
{/foreach}

<form method="post" action={'setup/datatype'|ezurl}>
<input type="hidden" name="Submitted" value="1" />

<h2>{'The datatype'|i18n('design/standard/setup')}</h2>
<p><label>{'Extension name'|i18n('design/standard/setup')}: <input type="text" name="name" value="{$wizard_settings.name|wash}" /></label></p>
<p><label>{'Datatype identifier'|i18n('design/standard/setup')}: <input type="text" name="type" value="{$wizard_settings.type|wash}" /></label></p>
<p><label>{'Class name'|i18n('design/standard/setup')}: <input type="text" name="class" value="{$wizard_settings.class|wash}" /></label></p>
<p><label>{'Name in the class editor'|i18n('design/standard/setup')}: <input type="text" name="title" value="{$wizard_settings.title|wash}" /></label></p>

<h2>{'What it has to do'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_capabilities as $dw_cap}
    <li>
        <label>
            <input type="checkbox" name="Capabilities[]" value="{$dw_cap.key|wash}"{if $dw_cap.chosen} checked="checked"{/if} />
            {$dw_cap.label|wash} &ndash; {$dw_cap.summary|wash} ({$dw_cap.count} {'methods'|i18n('design/standard/setup')})
        </label>
    </li>
{/foreach}
</ul>

<h2>{'Where the value lives'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_storage as $dw_column}
    <li>
        <label>
            <input type="checkbox" name="Storage[]" value="{$dw_column.key|wash}"{if $dw_column.chosen} checked="checked"{/if} />
            <code>{$dw_column.label|wash}</code> &ndash; {$dw_column.what|wash}
        </label>
    </li>
{/foreach}
</ul>

<h2>{'What goes in it'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_parts as $dw_key => $dw_part}
    <li>
        <label>
            <input type="checkbox" name="Parts[]" value="{$dw_key|wash}"{if $wizard_settings.parts[$dw_key]} checked="checked"{/if} />
            {$dw_part.label|wash} &ndash; {$dw_part.description|wash}
        </label>
    </li>
{/foreach}
</ul>

<h2>{'What will be written'|i18n('design/standard/setup')} ({$wizard_method_count})</h2>
<ul>
{foreach $wizard_methods as $dw_method}
    <li><code>{$dw_method.signature|wash}</code> &ndash; {$dw_method.what|wash}</li>
{/foreach}
</ul>

{if $wizard_file_count|gt( 0 )}
<h2>{'Every file, before it is written'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_files as $dw_file}
    <li><code>{$dw_file.path|wash}</code> &ndash; {$dw_file.lines} {'lines'|i18n('design/standard/setup')}</li>
{/foreach}
</ul>
{/if}

<p>
    {if $wizard_ready}<input type="submit" name="CreateButton" value="{'Create in extension/'|i18n('design/standard/setup')}" />{/if}
    <input type="submit" name="PreviewButton" value="{'Refresh preview'|i18n('design/standard/setup')}" />
</p>
</form>
