{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{'Kernel override wizard'|i18n('design/standard/setup')}</h1>
<p class="warning">
    {'An override is not a subclass. It replaces the kernel class under the same name, so nothing is inherited and every fix the kernel makes to that class afterwards is one this site does not get. Almost everything here has a lighter way in.'|i18n('design/standard/setup')}
</p>
<p>{$wizard_readiness.message|wash}</p>

{foreach $wizard_problems as $ko_problem}
<p class="warning">{$ko_problem|wash}</p>
{/foreach}

<form method="post" action={'setup/kerneloverride'|ezurl}>
<input type="hidden" name="Submitted" value="1" />

<p><label>{'Find a kernel class'|i18n('design/standard/setup')}: <input type="text" name="find" value="{$wizard_settings.find|wash}" /></label></p>

{if $wizard_match_count|gt( 0 )}
<ul>
{foreach $wizard_matches as $ko_match}
    <li><label><input type="radio" name="class" value="{$ko_match.class|wash}"{if $ko_match.current} checked="checked"{/if} />
        <code>{$ko_match.class|wash}</code> &ndash; {$ko_match.path|wash}</label></li>
{/foreach}
</ul>
{/if}

<p><label>{'Extension name'|i18n('design/standard/setup')}: <input type="text" name="name" value="{$wizard_settings.name|wash}" /></label></p>
<p><label>{'Why an override'|i18n('design/standard/setup')}:<br /><textarea name="reason" rows="3" cols="60">{$wizard_settings.reason|wash}</textarea></label></p>

{if $wizard_file_count|gt( 0 )}
<h2>{'Every file, before it is written'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_files as $ko_file}
    <li><code>{$ko_file.path|wash}</code> &ndash; {$ko_file.lines} {'lines'|i18n('design/standard/setup')}</li>
{/foreach}
</ul>
{/if}

<p>
    {if $wizard_ready}<input type="submit" name="CreateButton" value="{'Create in extension/'|i18n('design/standard/setup')}" />{/if}
    <input type="submit" name="PreviewButton" value="{'Find'|i18n('design/standard/setup')}" />
</p>
</form>
