{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{'Module wizard'|i18n('design/standard/setup')}</h1>
<p>{'A module is a declaration, a script per view, a template per view, and the two ini lines that make the kernel look for any of it.'|i18n('design/standard/setup')}</p>

{foreach $wizard_problems as $mw_problem}
<p class="warning">{$mw_problem|wash}</p>
{/foreach}

<form method="post" action={'setup/modulewizard'|ezurl}>
<input type="hidden" name="Submitted" value="1" />

<p><label>{'Extension name'|i18n('design/standard/setup')}: <input type="text" name="name" value="{$wizard_settings.name|wash}" /></label></p>
<p><label>{'Module name'|i18n('design/standard/setup')}: <input type="text" name="module" value="{$wizard_settings.module|wash}" /></label></p>
<p><label>{'Views'|i18n('design/standard/setup')}:<br /><textarea name="views" rows="4" cols="50">{$wizard_raw.views|wash}</textarea></label></p>
<p><label>{'Policies'|i18n('design/standard/setup')}:<br /><textarea name="policies" rows="3" cols="50">{$wizard_raw.policies|wash}</textarea></label></p>

<h2>{'What that produces'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_views as $mw_view}
    <li><code>{$mw_view.address|wash}</code> &ndash;
        {if $mw_view.policies|count|eq( 0 )}{'no policy check'|i18n('design/standard/setup')}
        {else}{'needs'|i18n('design/standard/setup')} {foreach $mw_view.policies as $mw_policy}<code>{$mw_policy|wash}</code> {/foreach}{/if}
    </li>
{/foreach}
</ul>

{if $wizard_file_count|gt( 0 )}
<h2>{'Every file, before it is written'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_files as $mw_file}
    <li><code>{$mw_file.path|wash}</code> &ndash; {$mw_file.lines} {'lines'|i18n('design/standard/setup')}</li>
{/foreach}
</ul>
{/if}

<p>
    {if $wizard_ready}<input type="submit" name="CreateButton" value="{'Create in extension/'|i18n('design/standard/setup')}" />{/if}
    <input type="submit" name="PreviewButton" value="{'Refresh preview'|i18n('design/standard/setup')}" />
</p>
</form>
