{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{'Extension point survey'|i18n('design/standard/setup')}</h1>
<p>{'What is actually on this installation, read off disk on every request.'|i18n('design/standard/setup')}</p>

<p>
    {$survey_counts.total} {'extension points found'|i18n('design/standard/setup')},
    {$survey_counts.ini} {'ini files read'|i18n('design/standard/setup')}.
</p>

<ul>
{foreach $survey_tabs as $sv_tab}
    <li>
        {if $sv_tab.current}<strong>{$sv_tab.title|wash} ({$sv_tab.count})</strong>
        {else}<a href={$sv_tab.url|ezurl}>{$sv_tab.title|wash} ({$sv_tab.count})</a>{/if}
    </li>
{/foreach}
</ul>

<h2>{$survey_section.title|wash}</h2>
<p>{$survey_section.what|wash}</p>

<table border="1" cellpadding="4" cellspacing="0">
<tr>
    <th>{'Where'|i18n('design/standard/setup')}</th>
    <th>{'Section'|i18n('design/standard/setup')}</th>
    <th>{'Setting'|i18n('design/standard/setup')}</th>
    <th>{'Value'|i18n('design/standard/setup')}</th>
    <th>{'Declared in'|i18n('design/standard/setup')}</th>
</tr>
{foreach $survey_rows as $sv_row}
<tr>
    <td><code>{$sv_row.one|wash}</code></td>
    <td><code>{$sv_row.two|wash}</code></td>
    <td><code>{$sv_row.three|wash}</code></td>
    <td><code>{$sv_row.four|wash}</code></td>
    <td><code>{$sv_row.note|wash}</code></td>
</tr>
{/foreach}
</table>

{if $survey_pages|count|gt( 0 )}
<p>
{foreach $survey_pages as $sv_page}
    {if $sv_page.current}<strong>{$sv_page.from}-{$sv_page.to}</strong>
    {else}<a href={$sv_page.url|ezurl}>{$sv_page.from}-{$sv_page.to}</a>{/if}
{/foreach}
</p>
{/if}
