{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{'Settings extension wizard'|i18n('design/standard/setup')}</h1>
<p>{'An extension that is mostly ini files: image aliases, event listeners, view cache rules, information collection, trigger operations and siteaccess settings.'|i18n('design/standard/setup')}</p>

{foreach $wizard_problems as $se_problem}
<p class="warning">{$se_problem|wash}</p>
{/foreach}

<form method="post" action={'setup/settingsextension'|ezurl}>
<input type="hidden" name="Submitted" value="1" />

<h2>{'What this extension says'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_topics as $se_topic}
    <li><label><input type="checkbox" name="Parts[]" value="{$se_topic.key|wash}"{if $se_topic.chosen} checked="checked"{/if} />
        {$se_topic.label|wash} (<code>{$se_topic.ini|wash}</code>) &ndash; {$se_topic.summary|wash}</label></li>
{/foreach}
</ul>

<p><label>{'Extension name'|i18n('design/standard/setup')}: <input type="text" name="name" value="{$wizard_settings.name|wash}" /></label></p>
<p><label>{'Image aliases'|i18n('design/standard/setup')}:<br /><textarea name="aliases" rows="3" cols="50">{$wizard_raw.aliases|wash}</textarea></label></p>
<p><label>{'View cache rules'|i18n('design/standard/setup')}:<br /><textarea name="rules" rows="3" cols="50">{$wizard_raw.rules|wash}</textarea></label></p>
<p><label>{'Information collection'|i18n('design/standard/setup')}:<br /><textarea name="forms" rows="3" cols="50">{$wizard_raw.forms|wash}</textarea></label></p>
<p><label>{'Trigger operations'|i18n('design/standard/setup')}: <input type="text" name="operations" value="{$wizard_raw.operations|wash}" /></label></p>
<p><label>{'Siteaccess'|i18n('design/standard/setup')}: <input type="text" name="siteaccess" value="{$wizard_settings.siteaccess|wash}" /></label></p>
<p><label>{'Siteaccess settings'|i18n('design/standard/setup')}:<br /><textarea name="overrides" rows="3" cols="50">{$wizard_raw.overrides|wash}</textarea></label></p>

<h2>{'Event listeners'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_event_groups as $se_group}
{foreach $se_group.events as $se_event}
    <li><label><input type="checkbox" name="Events[]" value="{$se_event.event|wash}"{if $se_event.chosen} checked="checked"{/if} />
        <code>{$se_event.event|wash}</code> ({$se_event.kind|wash}) &ndash; {$se_event.what|wash}</label></li>
{/foreach}
{/foreach}
</ul>

{if $wizard_file_count|gt( 0 )}
<h2>{'Every file, before it is written'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_files as $se_file}
    <li><code>{$se_file.path|wash}</code> &ndash; {$se_file.lines} {'lines'|i18n('design/standard/setup')}</li>
{/foreach}
</ul>
{/if}

<p>
    {if $wizard_ready}<input type="submit" name="CreateButton" value="{'Create in extension/'|i18n('design/standard/setup')}" />{/if}
    <input type="submit" name="PreviewButton" value="{'Refresh preview'|i18n('design/standard/setup')}" />
</p>
</form>
