{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h1>{'Template extension wizard'|i18n('design/standard/setup')}</h1>
<p>
    {'An operator takes a value and gives one back. A function writes output where it stands. A fetch function reads something, with a policy check first. A fetch alias is a fetch with its arguments already decided.'|i18n('design/standard/setup')}
</p>

{foreach $wizard_problems as $tw_problem}
<p class="warning">{$tw_problem|wash}</p>
{/foreach}

<form method="post" action={'setup/templateoperator'|ezurl}>
<input type="hidden" name="Submitted" value="1" />

<h2>{'What to add'|i18n('design/standard/setup')}</h2>
<p><label>{'Operators'|i18n('design/standard/setup')}: <input type="text" name="operators" value="{$wizard_raw.operators|wash}" /></label></p>
<p><label>{'Functions'|i18n('design/standard/setup')}: <input type="text" name="functions" value="{$wizard_raw.functions|wash}" /></label></p>
<p><label>{'Fetch functions'|i18n('design/standard/setup')}: <input type="text" name="fetches" value="{$wizard_raw.fetches|wash}" /></label></p>
<p><label>{'Fetch aliases'|i18n('design/standard/setup')}: <input type="text" name="aliases" value="{$wizard_raw.aliases|wash}" /></label></p>
<p><label>{'Parameters, one per line: name type required'|i18n('design/standard/setup')}:<br />
   <textarea name="parameters" rows="4" cols="40">{$wizard_raw.parameters|wash}</textarea></label></p>
<p><label><input type="checkbox" name="UseInput" value="1"{if $wizard_settings.input} checked="checked"{/if} /> {'Operators take input'|i18n('design/standard/setup')}</label></p>
<p><label><input type="checkbox" name="UseOutput" value="1"{if $wizard_settings.output} checked="checked"{/if} /> {'Operators produce output'|i18n('design/standard/setup')}</label></p>
<p><label><input type="checkbox" name="HasChildren" value="1"{if $wizard_settings.children} checked="checked"{/if} /> {'Functions have a body'|i18n('design/standard/setup')}</label></p>

<h2>{'The extension'|i18n('design/standard/setup')}</h2>
<p><label>{'Extension name'|i18n('design/standard/setup')}: <input type="text" name="name" value="{$wizard_settings.name|wash}" /></label></p>
<p><label>{'Class name'|i18n('design/standard/setup')}: <input type="text" name="class" value="{$wizard_settings.class|wash}" /></label></p>
<p><label>{'Module for the fetches'|i18n('design/standard/setup')}: <input type="text" name="module" value="{$wizard_settings.module|wash}" /></label></p>

<h2>{'What a template will write'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_usage as $tw_use}
    <li><code>{$tw_use.example|wash}</code> &ndash; {$tw_use.what|wash}</li>
{/foreach}
</ul>

{if $wizard_file_count|gt( 0 )}
<h2>{'Every file, before it is written'|i18n('design/standard/setup')}</h2>
<ul>
{foreach $wizard_files as $tw_file}
    <li><code>{$tw_file.path|wash}</code> &ndash; {$tw_file.lines} {'lines'|i18n('design/standard/setup')}</li>
{/foreach}
</ul>
{/if}

<p>
    {if $wizard_ready}<input type="submit" name="CreateButton" value="{'Create in extension/'|i18n('design/standard/setup')}" />{/if}
    <input type="submit" name="PreviewButton" value="{'Refresh preview'|i18n('design/standard/setup')}" />
</p>
</form>
