{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* foreach and a literal include: inside a named section the variables were looked up in the section's namespace,
   and an include whose uri is computed does not get the variables passed to it *}
{def $handler_items = fetch( 'notification', 'digest_items', hash( 'date', $date.timestamp, 'address', $address, 'handler', $handler.id_string ) )}
{foreach $handler_items as $digest_item}
{append-block scope=global variable=collection_item_id_list}{$digest_item.id}{/append-block}
{include handler=$handler collection_item=$digest_item uri='design:notification/handler/ezsubtree/view/digest_element_plain.tpl'}


{/foreach}
{undef $handler_items}
