{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* One collaboration item in a digest. Variables: collection_item. *}
{def $collaboration_item = fetch( 'notification', 'event_content', hash( 'event_id', $collection_item.event_id ) )}
{if $collaboration_item}
- {$collaboration_item.title}
  {"The item can be viewed by using the URL below."|i18n('design/standard/notification')}
  http://{ezini("SiteSettings","SiteURL")}{concat("collaboration/item/full/",$collaboration_item.id)|ezurl(no)}

{/if}
{undef $collaboration_item}
