{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* The collaboration items of a digest (the person chose a daily or weekly summary of "Collaboration and approvals"
   on the e-mail preference page). Variables: handler, date, address. *}
{def $handler_items = fetch( 'notification', 'digest_items', hash( 'date', $date.timestamp, 'address', $address, 'handler', $handler.id_string ) )}
{if $handler_items|count|gt( 0 )}
{"Collaboration and approvals"|i18n('design/standard/notification')}:

{foreach $handler_items as $digest_item}
{append-block scope=global variable=collection_item_id_list}{$digest_item.id}{/append-block}
{include handler=$handler collection_item=$digest_item uri='design:notification/handler/ezcollaboration/view/digest_element_plain.tpl'}
{/foreach}
{/if}
{undef $handler_items}
