{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* Only a URL eZURLType accepts as a link target becomes a PDF link; a script
   or data URL is printed as text. *}
{if $attribute.display_info.view.url_is_linkable}
{pdf(link, hash(url, $attribute.content,
                text, $attribute.data_text|wash(pdf)))}
{else}
{pdf(text, $attribute.data_text|wash(pdf))}
{/if}