{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{section show=$validation_error}
<div class="warning">
<h2>{'Input did not validate'|i18n( 'design/admin/settings' )}</h2>
    {switch match=$validation_error_type}
    {case match='empty'}
        <p>{'%validation_field is empty'|i18n( 'design/admin/settings',, hash( '%validation_field', $validation_field ) )}</p>
    {/case}
    {case match='variable_exists'}
        <p>{'Variable %setting already exists in section %section'|i18n( 'design/admin/settings',, hash( '%setting', concat( '<em>', $setting_name|wash, '</em>' ), '%section', concat( '<em>', $block, '</em>' ) ) )}</p>
        <p>{'Please choose another name that is not already taken'|i18n( 'design/admin/settings' )}</p>
    {/case}
    {case match='contain_spaces'}
        <p>{'%validation_field is not allowed to contain spaces'|i18n( 'design/admin/settings',, hash( '%validation_field', $validation_field|wash ) )}</p>
    {/case}
    {case match='write_error'}
        <p>{'Writing setting %setting to %file failed'|i18n( 'design/admin/settings',, hash( '%setting', concat( '<em>', $setting_name|wash, '</em>' ), '%file', concat( '<em>', $filename, '</em>' ) ) )}</p>
        <p>{'Make sure you have proper permissions to %path and try again.'|i18n( 'design/admin/settings',, hash( '%path', $path ) )}</p>
    {/case}
    {case match='not_valid_name'}
        <p>{'Name contains illegal character(s).'|i18n( 'design/admin/settings' )} </p>
        <p>{'Name should only contain A-Z and 0-9.'|i18n( 'design/admin/settings' )}</p>
    {/case}
    {case match='not_string'}
        <p>{'%validation_field does not contain a valid string.'|i18n( 'design/admin/settings',, hash( '%validation_field', $validation_field ) )} </p>
        <p>{'If the string is all numbers use the \'numeric\' type instead.'|i18n( 'design/admin/settings' )}</p>
    {/case}
    {case match='not_numeric'}
        <p>{'%validation_field does not contain a valid numeric'|i18n( 'design/admin/settings',, hash( '%validation_field', $validation_field ) )}</p>
        <p>{'A valid numeric can only contain 0-9 and one . (dot).'|i18n( 'design/admin/settings' )} </p>
    {/case}
    {case match='not_array'}
        <p>{'%validation_field does not contain valid array'|i18n( 'design/admin/settings',, hash( '%validation_field', $validation_field ) )}</p>
    {/case}
    {case}
        <p>{$validation_error_message}</p>
    {/case}
    {/switch}
</div>
{/section}