{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* The print view of a node: its name and every attribute that has content, without navigation, buttons or children.
   It is what content/versionview/<object>/<version>/<language>/(view_mode)/print shows when content.ini
   [VersionView] ViewModes[] lists print, for a print or PDF layout of a draft before it is published; content/view
   shows it as content/view/print/<node>.
   A site overrides it per class in override.ini, for example:
     [print_article]
     Source=node/view/print.tpl
     MatchFile=print/article.tpl
     Subdir=templates
     Match[class_identifier]=article *}
{default content_object=$node.object
         content_version=$node.contentobject_version_object}

<div class="content-view-print class-{$content_object.class_identifier|wash}">
    <h1>{$node.name|wash}</h1>

    {foreach $content_version.contentobject_attributes as $print_attribute}
        {if $print_attribute.has_content}
        <div class="attribute-{$print_attribute.contentclass_attribute_identifier|wash}">
            <h2>{$print_attribute.contentclass_attribute_name|wash}</h2>
            {attribute_view_gui attribute=$print_attribute}
        </div>
        {/if}
    {/foreach}
</div>

{/default}
